// frontend/vue/primevue/minimal/src/components/AppSidebar.vue
<template>
  <aside class="app-sidebar" :class="{ collapsed: !visible }">
    <!-- Logo Section -->
    <div class="sidebar-header">
      <div class="logo-container">
        <i class="pi pi-box logo-icon"></i>
        <span v-if="visible" class="logo-text">AppTemplate</span>
      </div>
    </div>

    <!-- Navigation Menu -->
    <nav class="sidebar-nav">
      <!-- Main Menu Items (no section) -->
      <ul class="nav-list">
        <li v-for="item in mainMenuItems" :key="item.path">
          <router-link
            :to="item.path"
            class="nav-item"
            :class="{ active: isActive(item.path) }"
            v-tooltip.right="{ value: item.label, disabled: visible }"
          >
            <i :class="item.icon"></i>
            <span v-if="visible">{{ item.label }}</span>
          </router-link>
        </li>
      </ul>

      <!-- Sectioned Menu Items -->
      <div v-for="[sectionName, items] in sectionEntries" :key="sectionName" class="nav-section">
        <span v-if="visible" class="nav-section-title">{{ sectionName }}</span>
        <ul class="nav-list">
          <li v-for="item in items" :key="item.path">
            <router-link
              :to="item.path"
              class="nav-item"
              :class="{ active: isActive(item.path) }"
              v-tooltip.right="{ value: item.label, disabled: visible }"
            >
              <i :class="item.icon"></i>
              <span v-if="visible">{{ item.label }}</span>
            </router-link>
          </li>
        </ul>
      </div>
    </nav>
  </aside>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { menuItems } from '@/config/menuConfig'
import { useAuthStore } from '@/stores/auth'
import { filterMenuByRole, groupMenuBySection } from '@/utils/menuUtils'

const visible = defineModel('visible', { default: true })

const route = useRoute()
const authStore = useAuthStore()

// Filter and group menu items based on user role
const filteredItems = computed(() => filterMenuByRole(menuItems, authStore.user?.role))
const groupedItems = computed(() => groupMenuBySection(filteredItems.value))

// Get items without section (main menu) and items with sections
const mainMenuItems = computed(() => groupedItems.value.get(undefined) || [])
const sectionEntries = computed(() =>
  Array.from(groupedItems.value.entries()).filter(([key]) => key !== undefined)
)

const isActive = (path) => {
  return route.path === path || route.path.startsWith(path + '/')
}
</script>

<style scoped>
.app-sidebar {
  width: 260px;
  min-width: 260px;
  height: 100vh;
  background-color: var(--p-surface-card);
  border-right: 1px solid var(--p-surface-border);
  display: flex;
  flex-direction: column;
  position: fixed;
  left: 0;
  top: 0;
  z-index: 1000;
  transition: width 0.3s ease, min-width 0.3s ease;
}

.app-sidebar.collapsed {
  width: 64px;
  min-width: 64px;
}

.sidebar-header {
  padding: 1rem;
  border-bottom: 1px solid var(--p-surface-border);
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 60px;
}

.logo-container {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.logo-icon {
  font-size: 1.5rem;
  color: var(--p-primary-color);
}

.logo-text {
  font-size: 1.125rem;
  font-weight: 700;
  color: var(--p-text-color);
  white-space: nowrap;
}

.sidebar-nav {
  flex: 1;
  padding: 0.5rem 0;
  overflow-y: auto;
}

.nav-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.nav-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.75rem 1rem;
  color: var(--p-text-color);
  text-decoration: none;
  transition: all 0.2s ease;
  border-left: 3px solid transparent;
}

.collapsed .nav-item {
  justify-content: center;
  padding: 0.75rem;
}

.nav-item:hover {
  background-color: var(--p-surface-hover);
}

.nav-item.active {
  background-color: var(--p-primary-50);
  color: var(--p-primary-color);
  border-left-color: var(--p-primary-color);
  font-weight: 500;
}

.nav-item i {
  font-size: 1.125rem;
  width: 1.25rem;
  text-align: center;
}

.nav-section {
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px solid var(--p-surface-border);
}

.nav-section-title {
  display: block;
  padding: 0.5rem 1rem;
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  color: var(--p-text-muted-color);
  letter-spacing: 0.05em;
}

@media (max-width: 991px) {
  .app-sidebar {
    transform: translateX(-100%);
  }

  .app-sidebar:not(.collapsed) {
    transform: translateX(0);
    box-shadow: 2px 0 8px rgba(0, 0, 0, 0.15);
  }
}
</style>

// frontend/react/primereact/full/src/components/layout/AppSidebar.tsx
import { useLocation, useNavigate } from 'react-router-dom'
import { Tooltip } from 'primereact/tooltip'
import { useAuthStore } from '@/stores'
import { menuItems } from '@/config/menuConfig'
import { filterMenuByRole, groupMenuBySection } from '@/utils/menuUtils'

interface AppSidebarProps {
  collapsed: boolean
}

export function AppSidebar({ collapsed }: AppSidebarProps) {
  const location = useLocation()
  const navigate = useNavigate()
  const user = useAuthStore((state) => state.user)

  const filteredItems = filterMenuByRole(menuItems, user?.role)
  const groupedItems = groupMenuBySection(filteredItems)

  // Get items without section (main menu) and items with sections
  const mainMenuItems = groupedItems.get(undefined) || []
  const sectionEntries = Array.from(groupedItems.entries()).filter(([key]) => key !== undefined)

  const isActive = (path: string) => {
    return location.pathname === path || location.pathname.startsWith(path + '/')
  }

  const handleNavClick = (path: string) => {
    navigate(path)
  }

  return (
    <aside className={`app-sidebar ${collapsed ? 'collapsed' : ''}`}>
      {/* Logo Section */}
      <div className="sidebar-header">
        <div className="logo-container">
          <i className="pi pi-box logo-icon"></i>
          {!collapsed && <span className="logo-text">AppTemplate</span>}
        </div>
      </div>

      {/* Navigation Menu */}
      <nav className="sidebar-nav">
        {/* Main Menu Items (no section) */}
        <ul className="nav-list">
          {mainMenuItems.map((item) => (
            <li key={item.path}>
              <a
                className={`nav-item ${isActive(item.path) ? 'active' : ''}`}
                onClick={() => handleNavClick(item.path)}
                data-pr-tooltip={item.label}
                data-pr-position="right"
                data-pr-disabled={!collapsed}
              >
                <i className={item.icon}></i>
                {!collapsed && <span>{item.label}</span>}
              </a>
              {collapsed && <Tooltip target={`[data-pr-tooltip="${item.label}"]`} />}
            </li>
          ))}
        </ul>

        {/* Sectioned Menu Items */}
        {sectionEntries.map(([sectionName, items]) => (
          <div key={sectionName} className="nav-section">
            {!collapsed && <span className="nav-section-title">{sectionName}</span>}
            <ul className="nav-list">
              {items.map((item) => (
                <li key={item.path}>
                  <a
                    className={`nav-item ${isActive(item.path) ? 'active' : ''}`}
                    onClick={() => handleNavClick(item.path)}
                    data-pr-tooltip={item.label}
                    data-pr-position="right"
                    data-pr-disabled={!collapsed}
                  >
                    <i className={item.icon}></i>
                    {!collapsed && <span>{item.label}</span>}
                  </a>
                  {collapsed && <Tooltip target={`[data-pr-tooltip="${item.label}"]`} />}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </nav>
    </aside>
  )
}
