// frontend-primereact/src/pages/AuditLogs.tsx
import { useState, useEffect, useCallback } from 'react'
import { DataTable } from 'primereact/datatable'
import { Column } from 'primereact/column'
import { Button } from 'primereact/button'
import { Dialog } from 'primereact/dialog'
import { Dropdown } from 'primereact/dropdown'
import { Tag } from 'primereact/tag'
import { Card } from 'primereact/card'
import { Divider } from 'primereact/divider'
import { useNotificationStore } from '@/stores/notificationStore'
import { getAuditLogs, type AuditLog } from '@/services/auditLogService'

export default function AuditLogs() {
  const showError = useNotificationStore((state) => state.showError)

  const [loading, setLoading] = useState(false)
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([])

  // Filters
  const [entityFilter, setEntityFilter] = useState<string | null>(null)
  const [actionFilter, setActionFilter] = useState<string | null>(null)

  // Details dialog
  const [detailsVisible, setDetailsVisible] = useState(false)
  const [selectedLog, setSelectedLog] = useState<AuditLog | null>(null)

  const entityOptions = ['User', 'Department', 'UploadedFile']
  const actionOptions = ['Created', 'Updated', 'Deleted']

  const loadAuditLogs = useCallback(async () => {
    setLoading(true)
    try {
      const params: Record<string, string> = {}
      if (entityFilter) params.entityName = entityFilter
      if (actionFilter) params.action = actionFilter
      const data = await getAuditLogs(params)
      setAuditLogs(data || [])
    } catch {
      showError('Failed to load audit logs')
    } finally {
      setLoading(false)
    }
  }, [entityFilter, actionFilter, showError])

  useEffect(() => {
    loadAuditLogs()
  }, [loadAuditLogs])

  const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const getActionSeverity = (action: string): 'success' | 'info' | 'danger' | 'secondary' => {
    switch (action?.toLowerCase()) {
      case 'created':
        return 'success'
      case 'updated':
        return 'info'
      case 'deleted':
        return 'danger'
      default:
        return 'secondary'
    }
  }

  const formatJson = (jsonString: string | null): string | null => {
    if (!jsonString) return null
    try {
      return JSON.stringify(JSON.parse(jsonString), null, 2)
    } catch {
      return jsonString
    }
  }

  const showDetails = (log: AuditLog) => {
    setSelectedLog(log)
    setDetailsVisible(true)
  }

  const actionTemplate = (log: AuditLog) => (
    <Tag value={log.action} severity={getActionSeverity(log.action)} />
  )

  const timestampTemplate = (log: AuditLog) => formatDate(log.timestamp)

  const userIdTemplate = (log: AuditLog) => log.userId || '-'

  const actionsTemplate = (log: AuditLog) => (
    <Button
      icon="pi pi-eye"
      rounded
      text
      severity="info"
      onClick={() => showDetails(log)}
      tooltip="View Details"
      tooltipOptions={{ position: 'top' }}
    />
  )

  const renderHeader = () => (
    <div className="flex flex-wrap align-items-center justify-content-between gap-2">
      <div className="flex align-items-center gap-2">
        <i className="pi pi-history text-xl"></i>
        <span className="text-xl font-semibold">Audit Logs</span>
      </div>
      <Button
        icon="pi pi-refresh"
        rounded
        text
        onClick={loadAuditLogs}
        loading={loading}
      />
    </div>
  )

  const emptyMessage = (
    <div className="flex flex-column align-items-center p-5 text-color-secondary">
      <i className="pi pi-history text-5xl mb-3"></i>
      <span>No audit logs found</span>
    </div>
  )

  const dialogFooter = (
    <Button label="Close" onClick={() => setDetailsVisible(false)} />
  )

  return (
    <div className="p-3">
      <Card>
        {/* Filters */}
        <div className="flex flex-wrap gap-3 mb-4">
          <Dropdown
            value={entityFilter}
            options={entityOptions}
            onChange={(e) => setEntityFilter(e.value)}
            placeholder="Filter by Entity"
            showClear
            className="w-12rem"
          />
          <Dropdown
            value={actionFilter}
            options={actionOptions}
            onChange={(e) => setActionFilter(e.value)}
            placeholder="Filter by Action"
            showClear
            className="w-12rem"
          />
          <Button label="Apply" icon="pi pi-filter" onClick={loadAuditLogs} />
        </div>

        <DataTable
          value={auditLogs}
          loading={loading}
          paginator
          rows={10}
          rowsPerPageOptions={[5, 10, 25, 50]}
          dataKey="id"
          header={renderHeader()}
          emptyMessage={emptyMessage}
          stripedRows
        >
          <Column field="entityName" header="Entity" sortable style={{ minWidth: '120px' }} />
          <Column field="entityId" header="Entity ID" sortable style={{ minWidth: '100px' }} />
          <Column header="Action" body={actionTemplate} sortable style={{ minWidth: '100px' }} />
          <Column header="User ID" body={userIdTemplate} sortable style={{ minWidth: '100px' }} />
          <Column header="Timestamp" body={timestampTemplate} sortable style={{ minWidth: '180px' }} />
          <Column header="Details" body={actionsTemplate} style={{ minWidth: '80px' }} />
        </DataTable>
      </Card>

      {/* Details Dialog */}
      <Dialog
        header="Audit Log Details"
        visible={detailsVisible}
        onHide={() => setDetailsVisible(false)}
        footer={dialogFooter}
        style={{ width: '50rem' }}
        modal
      >
        {selectedLog && (
          <div className="flex flex-column gap-3">
            <div className="grid">
              <div className="col-6">
                <strong>Entity:</strong> {selectedLog.entityName}
              </div>
              <div className="col-6">
                <strong>Entity ID:</strong> {selectedLog.entityId}
              </div>
              <div className="col-6">
                <strong>Action:</strong>{' '}
                <Tag value={selectedLog.action} severity={getActionSeverity(selectedLog.action)} />
              </div>
              <div className="col-6">
                <strong>User ID:</strong> {selectedLog.userId || '-'}
              </div>
              <div className="col-12">
                <strong>Timestamp:</strong> {formatDate(selectedLog.timestamp)}
              </div>
            </div>

            <Divider />

            {selectedLog.oldValues && (
              <div>
                <strong>Old Values:</strong>
                <div className="surface-100 p-3 border-round mt-2" style={{ overflow: 'auto' }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                    {formatJson(selectedLog.oldValues)}
                  </pre>
                </div>
              </div>
            )}

            {selectedLog.newValues && (
              <div>
                <strong>New Values:</strong>
                <div className="surface-100 p-3 border-round mt-2" style={{ overflow: 'auto' }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                    {formatJson(selectedLog.newValues)}
                  </pre>
                </div>
              </div>
            )}

            {selectedLog.affectedColumns && (
              <div>
                <strong>Affected Columns:</strong>
                <div className="surface-100 p-3 border-round mt-2">
                  <pre style={{ margin: 0 }}>{formatJson(selectedLog.affectedColumns)}</pre>
                </div>
              </div>
            )}
          </div>
        )}
      </Dialog>
    </div>
  )
}

// frontend-primevue/src/pages/audit-logs/index.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { FilterMatchMode } from '@primevue/core/api'
import { getAuditLogs } from '@/services/auditLogService'
import { useToast } from 'primevue/usetoast'

const toast = useToast()

const loading = ref(false)
const auditLogs = ref([])

const filters = ref({
  global: { value: null, matchMode: FilterMatchMode.CONTAINS },
})

// Filter options
const entityFilter = ref(null)
const actionFilter = ref(null)
const entityOptions = ['User', 'Department', 'UploadedFile']
const actionOptions = ['Created', 'Updated', 'Deleted']

async function loadAuditLogs() {
  loading.value = true
  try {
    const params = {}
    if (entityFilter.value) params.entityName = entityFilter.value
    if (actionFilter.value) params.action = actionFilter.value
    auditLogs.value = await getAuditLogs(params)
  } catch {
    toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to load audit logs', life: 3000 })
  } finally {
    loading.value = false
  }
}

function formatDate(dateString) {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function getActionSeverity(action) {
  switch (action?.toLowerCase()) {
    case 'created':
      return 'success'
    case 'updated':
      return 'info'
    case 'deleted':
      return 'danger'
    default:
      return 'secondary'
  }
}

function formatJson(jsonString) {
  if (!jsonString) return null
  try {
    return JSON.stringify(JSON.parse(jsonString), null, 2)
  } catch {
    return jsonString
  }
}

// Details dialog
const detailsDialog = ref(false)
const selectedLog = ref(null)

function showDetails(log) {
  selectedLog.value = log
  detailsDialog.value = true
}

onMounted(() => {
  loadAuditLogs()
})
</script>

<template>
  <div class="p-4">
    <Card>
      <template #title>
        <div class="flex align-items-center justify-content-between">
          <div class="flex align-items-center gap-2">
            <i class="pi pi-history text-xl"></i>
            <span>Audit Logs</span>
          </div>
          <Button icon="pi pi-refresh" text rounded @click="loadAuditLogs" :loading="loading" />
        </div>
      </template>

      <template #content>
        <!-- Filters -->
        <div class="flex flex-wrap gap-3 mb-4">
          <Dropdown
            v-model="entityFilter"
            :options="entityOptions"
            placeholder="Filter by Entity"
            showClear
            class="w-12rem"
          />
          <Dropdown
            v-model="actionFilter"
            :options="actionOptions"
            placeholder="Filter by Action"
            showClear
            class="w-12rem"
          />
          <IconField>
            <InputIcon class="pi pi-search" />
            <InputText v-model="filters['global'].value" placeholder="Search..." />
          </IconField>
          <Button label="Apply" icon="pi pi-filter" @click="loadAuditLogs" />
        </div>

        <!-- Data Table -->
        <DataTable
          :value="auditLogs"
          :loading="loading"
          :filters="filters"
          :globalFilterFields="['entityName', 'entityId', 'action']"
          paginator
          :rows="10"
          :rowsPerPageOptions="[5, 10, 25, 50]"
          stripedRows
          dataKey="id"
        >
          <Column field="entityName" header="Entity" sortable style="min-width: 120px" />
          <Column field="entityId" header="Entity ID" sortable style="min-width: 100px" />
          <Column field="action" header="Action" sortable style="min-width: 100px">
            <template #body="{ data }">
              <Tag :value="data.action" :severity="getActionSeverity(data.action)" />
            </template>
          </Column>
          <Column field="userId" header="User ID" sortable style="min-width: 100px">
            <template #body="{ data }">
              {{ data.userId || '-' }}
            </template>
          </Column>
          <Column field="timestamp" header="Timestamp" sortable style="min-width: 180px">
            <template #body="{ data }">
              {{ formatDate(data.timestamp) }}
            </template>
          </Column>
          <Column header="Details" style="min-width: 80px">
            <template #body="{ data }">
              <Button icon="pi pi-eye" text rounded @click="showDetails(data)" />
            </template>
          </Column>

          <template #empty>
            <div class="flex flex-column align-items-center py-5 text-color-secondary">
              <i class="pi pi-history text-5xl mb-3"></i>
              <span>No audit logs found</span>
            </div>
          </template>
        </DataTable>
      </template>
    </Card>

    <!-- Details Dialog -->
    <Dialog v-model:visible="detailsDialog" header="Audit Log Details" :style="{ width: '50rem' }" modal>
      <div v-if="selectedLog" class="flex flex-column gap-3">
        <div class="grid">
          <div class="col-6">
            <strong>Entity:</strong> {{ selectedLog.entityName }}
          </div>
          <div class="col-6">
            <strong>Entity ID:</strong> {{ selectedLog.entityId }}
          </div>
          <div class="col-6">
            <strong>Action:</strong>
            <Tag :value="selectedLog.action" :severity="getActionSeverity(selectedLog.action)" class="ml-2" />
          </div>
          <div class="col-6">
            <strong>User ID:</strong> {{ selectedLog.userId || '-' }}
          </div>
          <div class="col-12">
            <strong>Timestamp:</strong> {{ formatDate(selectedLog.timestamp) }}
          </div>
        </div>

        <Divider />

        <div v-if="selectedLog.oldValues">
          <strong>Old Values:</strong>
          <div class="surface-100 p-3 border-round mt-2" style="overflow-x: auto">
            <pre style="margin: 0; white-space: pre-wrap">{{ formatJson(selectedLog.oldValues) }}</pre>
          </div>
        </div>

        <div v-if="selectedLog.newValues">
          <strong>New Values:</strong>
          <div class="surface-100 p-3 border-round mt-2" style="overflow-x: auto">
            <pre style="margin: 0; white-space: pre-wrap">{{ formatJson(selectedLog.newValues) }}</pre>
          </div>
        </div>

        <div v-if="selectedLog.affectedColumns">
          <strong>Affected Columns:</strong>
          <div class="surface-100 p-3 border-round mt-2">
            <pre style="margin: 0">{{ formatJson(selectedLog.affectedColumns) }}</pre>
          </div>
        </div>
      </div>

      <template #footer>
        <Button label="Close" @click="detailsDialog = false" />
      </template>
    </Dialog>
  </div>
</template>
