// frontend-primereact/src/pages/AuditLogs.tsx
import { useState, useEffect, useCallback } from 'react'
import { DataTable } from 'primereact/datatable'
import { Column } from 'primereact/column'
import { Button } from 'primereact/button'
import { Dialog } from 'primereact/dialog'
import { Dropdown } from 'primereact/dropdown'
import { Tag } from 'primereact/tag'
import { Card } from 'primereact/card'
import { Divider } from 'primereact/divider'
import { useNotificationStore } from '@/stores/notificationStore'
import { getAuditLogs, type AuditLog } from '@/services/auditLogService'

export default function AuditLogs() {
  const showError = useNotificationStore((state) => state.showError)

  const [loading, setLoading] = useState(false)
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([])

  // Filters
  const [entityFilter, setEntityFilter] = useState<string | null>(null)
  const [actionFilter, setActionFilter] = useState<string | null>(null)

  // Details dialog
  const [detailsVisible, setDetailsVisible] = useState(false)
  const [selectedLog, setSelectedLog] = useState<AuditLog | null>(null)

  const entityOptions = ['User', 'Department', 'UploadedFile']
  const actionOptions = ['Created', 'Updated', 'Deleted']

  const loadAuditLogs = useCallback(async () => {
    setLoading(true)
    try {
      const params: Record<string, string> = {}
      if (entityFilter) params.entityName = entityFilter
      if (actionFilter) params.action = actionFilter
      const data = await getAuditLogs(params)
      setAuditLogs(data || [])
    } catch {
      showError('Failed to load audit logs')
    } finally {
      setLoading(false)
    }
  }, [entityFilter, actionFilter, showError])

  useEffect(() => {
    loadAuditLogs()
  }, [loadAuditLogs])

  const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const getActionSeverity = (action: string): 'success' | 'info' | 'danger' | 'secondary' => {
    switch (action?.toLowerCase()) {
      case 'created':
        return 'success'
      case 'updated':
        return 'info'
      case 'deleted':
        return 'danger'
      default:
        return 'secondary'
    }
  }

  const formatJson = (jsonString: string | null): string | null => {
    if (!jsonString) return null
    try {
      return JSON.stringify(JSON.parse(jsonString), null, 2)
    } catch {
      return jsonString
    }
  }

  const showDetails = (log: AuditLog) => {
    setSelectedLog(log)
    setDetailsVisible(true)
  }

  const actionTemplate = (log: AuditLog) => (
    <Tag value={log.action} severity={getActionSeverity(log.action)} />
  )

  const timestampTemplate = (log: AuditLog) => formatDate(log.timestamp)

  const userIdTemplate = (log: AuditLog) => log.userId || '-'

  const actionsTemplate = (log: AuditLog) => (
    <Button
      icon="pi pi-eye"
      rounded
      text
      severity="info"
      onClick={() => showDetails(log)}
      tooltip="View Details"
      tooltipOptions={{ position: 'top' }}
    />
  )

  const renderHeader = () => (
    <div className="flex flex-wrap align-items-center justify-content-between gap-2">
      <div className="flex align-items-center gap-2">
        <i className="pi pi-history text-xl"></i>
        <span className="text-xl font-semibold">Audit Logs</span>
      </div>
      <Button
        icon="pi pi-refresh"
        rounded
        text
        onClick={loadAuditLogs}
        loading={loading}
      />
    </div>
  )

  const emptyMessage = (
    <div className="flex flex-column align-items-center p-5 text-color-secondary">
      <i className="pi pi-history text-5xl mb-3"></i>
      <span>No audit logs found</span>
    </div>
  )

  const dialogFooter = (
    <Button label="Close" onClick={() => setDetailsVisible(false)} />
  )

  return (
    <div className="p-3">
      <Card>
        {/* Filters */}
        <div className="flex flex-wrap gap-3 mb-4">
          <Dropdown
            value={entityFilter}
            options={entityOptions}
            onChange={(e) => setEntityFilter(e.value)}
            placeholder="Filter by Entity"
            showClear
            className="w-12rem"
          />
          <Dropdown
            value={actionFilter}
            options={actionOptions}
            onChange={(e) => setActionFilter(e.value)}
            placeholder="Filter by Action"
            showClear
            className="w-12rem"
          />
          <Button label="Apply" icon="pi pi-filter" onClick={loadAuditLogs} />
        </div>

        <DataTable
          value={auditLogs}
          loading={loading}
          paginator
          rows={10}
          rowsPerPageOptions={[5, 10, 25, 50]}
          dataKey="id"
          header={renderHeader()}
          emptyMessage={emptyMessage}
          stripedRows
        >
          <Column field="entityName" header="Entity" sortable style={{ minWidth: '120px' }} />
          <Column field="entityId" header="Entity ID" sortable style={{ minWidth: '100px' }} />
          <Column header="Action" body={actionTemplate} sortable style={{ minWidth: '100px' }} />
          <Column header="User ID" body={userIdTemplate} sortable style={{ minWidth: '100px' }} />
          <Column header="Timestamp" body={timestampTemplate} sortable style={{ minWidth: '180px' }} />
          <Column header="Details" body={actionsTemplate} style={{ minWidth: '80px' }} />
        </DataTable>
      </Card>

      {/* Details Dialog */}
      <Dialog
        header="Audit Log Details"
        visible={detailsVisible}
        onHide={() => setDetailsVisible(false)}
        footer={dialogFooter}
        style={{ width: '50rem' }}
        modal
      >
        {selectedLog && (
          <div className="flex flex-column gap-3">
            <div className="grid">
              <div className="col-6">
                <strong>Entity:</strong> {selectedLog.entityName}
              </div>
              <div className="col-6">
                <strong>Entity ID:</strong> {selectedLog.entityId}
              </div>
              <div className="col-6">
                <strong>Action:</strong>{' '}
                <Tag value={selectedLog.action} severity={getActionSeverity(selectedLog.action)} />
              </div>
              <div className="col-6">
                <strong>User ID:</strong> {selectedLog.userId || '-'}
              </div>
              <div className="col-12">
                <strong>Timestamp:</strong> {formatDate(selectedLog.timestamp)}
              </div>
            </div>

            <Divider />

            {selectedLog.oldValues && (
              <div>
                <strong>Old Values:</strong>
                <div className="surface-100 p-3 border-round mt-2" style={{ overflow: 'auto' }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                    {formatJson(selectedLog.oldValues)}
                  </pre>
                </div>
              </div>
            )}

            {selectedLog.newValues && (
              <div>
                <strong>New Values:</strong>
                <div className="surface-100 p-3 border-round mt-2" style={{ overflow: 'auto' }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap' }}>
                    {formatJson(selectedLog.newValues)}
                  </pre>
                </div>
              </div>
            )}

            {selectedLog.affectedColumns && (
              <div>
                <strong>Affected Columns:</strong>
                <div className="surface-100 p-3 border-round mt-2">
                  <pre style={{ margin: 0 }}>{formatJson(selectedLog.affectedColumns)}</pre>
                </div>
              </div>
            )}
          </div>
        )}
      </Dialog>
    </div>
  )
}

// frontend-vuetify/src/pages/audit-logs/index.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import { getAuditLogs } from '@/services/auditLogService'
import { useToastStore } from '@/stores/toast'

const toastStore = useToastStore()

const loading = ref(false)
const auditLogs = ref([])
const search = ref('')
const itemsPerPage = ref(10)

// Filters
const filters = ref({
  entityName: '',
  action: '',
  fromDate: null,
  toDate: null,
})

const entityNames = ['User', 'Department', 'UploadedFile']
const actions = ['Created', 'Updated', 'Deleted']

const headers = [
  { title: 'Entity', key: 'entityName', sortable: true },
  { title: 'Entity ID', key: 'entityId', sortable: true },
  { title: 'Action', key: 'action', sortable: true },
  { title: 'User ID', key: 'userId', sortable: true },
  { title: 'Timestamp', key: 'timestamp', sortable: true },
  { title: 'Details', key: 'actions', sortable: false, align: 'center' },
]

const filteredLogs = computed(() => {
  if (!search.value) return auditLogs.value
  const searchLower = search.value.toLowerCase()
  return auditLogs.value.filter(
    (log) =>
      log.entityName.toLowerCase().includes(searchLower) ||
      log.entityId.toLowerCase().includes(searchLower) ||
      log.action.toLowerCase().includes(searchLower)
  )
})

async function loadAuditLogs() {
  loading.value = true
  try {
    const params = {}
    if (filters.value.entityName) params.entityName = filters.value.entityName
    if (filters.value.action) params.action = filters.value.action
    if (filters.value.fromDate) params.fromDate = filters.value.fromDate
    if (filters.value.toDate) params.toDate = filters.value.toDate

    auditLogs.value = await getAuditLogs(params)
  } catch {
    toastStore.showError('Failed to load audit logs')
  } finally {
    loading.value = false
  }
}

function formatDate(dateString) {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function getActionColor(action) {
  switch (action?.toLowerCase()) {
    case 'created':
      return 'success'
    case 'updated':
      return 'info'
    case 'deleted':
      return 'error'
    default:
      return 'secondary'
  }
}

function formatJson(jsonString) {
  if (!jsonString) return null
  try {
    return JSON.stringify(JSON.parse(jsonString), null, 2)
  } catch {
    return jsonString
  }
}

// Details dialog
const detailsDialog = ref(false)
const selectedLog = ref(null)

function showDetails(log) {
  selectedLog.value = log
  detailsDialog.value = true
}

onMounted(() => {
  loadAuditLogs()
})
</script>

<template>
  <v-container fluid>
    <v-card>
      <v-card-title class="d-flex align-center">
        <v-icon class="mr-2">mdi-history</v-icon>
        Audit Logs
        <v-spacer />
        <v-btn icon="mdi-refresh" variant="text" @click="loadAuditLogs" :loading="loading" />
      </v-card-title>

      <v-card-text>
        <!-- Filters -->
        <v-row class="mb-4">
          <v-col cols="12" md="3">
            <v-select
              v-model="filters.entityName"
              :items="entityNames"
              label="Entity"
              clearable
              density="compact"
              hide-details
            />
          </v-col>
          <v-col cols="12" md="3">
            <v-select
              v-model="filters.action"
              :items="actions"
              label="Action"
              clearable
              density="compact"
              hide-details
            />
          </v-col>
          <v-col cols="12" md="4">
            <v-text-field
              v-model="search"
              prepend-inner-icon="mdi-magnify"
              label="Search"
              density="compact"
              hide-details
              clearable
            />
          </v-col>
          <v-col cols="12" md="2">
            <v-btn color="primary" @click="loadAuditLogs" block>
              <v-icon left>mdi-filter</v-icon>
              Apply
            </v-btn>
          </v-col>
        </v-row>

        <!-- Data Table -->
        <v-data-table
          :headers="headers"
          :items="filteredLogs"
          :loading="loading"
          :items-per-page="itemsPerPage"
          class="elevation-1"
        >
          <template #item.action="{ item }">
            <v-chip :color="getActionColor(item.action)" size="small">
              {{ item.action }}
            </v-chip>
          </template>

          <template #item.userId="{ item }">
            {{ item.userId || '-' }}
          </template>

          <template #item.timestamp="{ item }">
            {{ formatDate(item.timestamp) }}
          </template>

          <template #item.actions="{ item }">
            <v-btn
              icon="mdi-eye"
              size="small"
              variant="text"
              @click="showDetails(item)"
            />
          </template>

          <template #no-data>
            <div class="text-center py-8">
              <v-icon size="64" color="grey-lighten-1">mdi-history</v-icon>
              <p class="text-grey mt-4">No audit logs found</p>
            </div>
          </template>
        </v-data-table>
      </v-card-text>
    </v-card>

    <!-- Details Dialog -->
    <v-dialog v-model="detailsDialog" max-width="800">
      <v-card v-if="selectedLog">
        <v-card-title>
          <v-icon class="mr-2">mdi-information</v-icon>
          Audit Log Details
        </v-card-title>
        <v-card-text>
          <v-row>
            <v-col cols="6">
              <strong>Entity:</strong> {{ selectedLog.entityName }}
            </v-col>
            <v-col cols="6">
              <strong>Entity ID:</strong> {{ selectedLog.entityId }}
            </v-col>
            <v-col cols="6">
              <strong>Action:</strong>
              <v-chip :color="getActionColor(selectedLog.action)" size="small" class="ml-2">
                {{ selectedLog.action }}
              </v-chip>
            </v-col>
            <v-col cols="6">
              <strong>User ID:</strong> {{ selectedLog.userId || '-' }}
            </v-col>
            <v-col cols="12">
              <strong>Timestamp:</strong> {{ formatDate(selectedLog.timestamp) }}
            </v-col>
          </v-row>

          <v-divider class="my-4" />

          <v-row v-if="selectedLog.oldValues">
            <v-col cols="12">
              <strong>Old Values:</strong>
              <v-sheet class="pa-3 mt-2 bg-grey-lighten-4 rounded" style="overflow-x: auto">
                <pre style="margin: 0; white-space: pre-wrap">{{ formatJson(selectedLog.oldValues) }}</pre>
              </v-sheet>
            </v-col>
          </v-row>

          <v-row v-if="selectedLog.newValues">
            <v-col cols="12">
              <strong>New Values:</strong>
              <v-sheet class="pa-3 mt-2 bg-grey-lighten-4 rounded" style="overflow-x: auto">
                <pre style="margin: 0; white-space: pre-wrap">{{ formatJson(selectedLog.newValues) }}</pre>
              </v-sheet>
            </v-col>
          </v-row>

          <v-row v-if="selectedLog.affectedColumns">
            <v-col cols="12">
              <strong>Affected Columns:</strong>
              <v-sheet class="pa-3 mt-2 bg-grey-lighten-4 rounded">
                <pre style="margin: 0">{{ formatJson(selectedLog.affectedColumns) }}</pre>
              </v-sheet>
            </v-col>
          </v-row>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="detailsDialog = false">Close</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>
