// frontend/vue/vuetify/full/src/pages/departments/index.vue
<template>
  <v-container fluid>
    <v-row>
      <v-col class="d-flex justify-end" cols="12">
        <v-btn color="primary" prepend-icon="mdi-plus" @click="openCreateDialog">
          Add Department
        </v-btn>
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12" md="6">
        <v-text-field
          v-model="search"
          clearable
          density="compact"
          hide-details
          label="Search departments..."
          prepend-inner-icon="mdi-magnify"
        />
      </v-col>
      <v-col cols="12" md="6">
        <v-select
          v-model="statusFilter"
          clearable
          density="compact"
          hide-details
          :items="statusOptions"
          label="Status"
        />
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12">
        <v-data-table
          :headers="headers"
          hover
          :items="filteredDepartments"
          :loading="departmentStore.loading"
        >
          <template #item.isActive="{ item }">
            <v-chip :color="item.isActive ? 'success' : 'error'" size="small">
              {{ item.isActive ? 'Active' : 'Inactive' }}
            </v-chip>
          </template>
          <template #item.actions="{ item }">
            <v-btn icon="mdi-pencil" size="small" variant="text" @click="openEditDialog(item)" />
            <v-btn
              color="error"
              icon="mdi-delete"
              size="small"
              variant="text"
              @click="confirmDelete(item)"
            />
          </template>
        </v-data-table>
      </v-col>
    </v-row>

    <!-- Create/Edit Dialog -->
    <v-dialog v-model="dialog" max-width="600">
      <v-card>
        <v-card-title>{{ isEditing ? 'Edit Department' : 'Create Department' }}</v-card-title>
        <v-card-text>
          <v-form ref="formRef">
            <v-text-field
              v-model="form.code"
              label="Code"
              :rules="[v => !!v || 'Code is required']"
            />
            <v-text-field
              v-model="form.name"
              label="Name"
              :rules="[v => !!v || 'Name is required']"
            />
            <v-textarea
              v-model="form.description"
              label="Description"
              rows="3"
            />
            <v-switch
              v-if="isEditing"
              v-model="form.isActive"
              color="success"
              label="Active"
            />
          </v-form>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="dialog = false">Cancel</v-btn>
          <v-btn color="primary" :loading="saving" @click="saveDepartment">Save</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
  import { useConfirmDialog } from '@/composables/useConfirmDialog'
  import { useDepartmentStore } from '@/stores/department'
  import { useNotificationStore } from '@/stores/notification'

  const departmentStore = useDepartmentStore()
  const notificationStore = useNotificationStore()
  const { confirm } = useConfirmDialog()

  const search = ref('')
  const statusFilter = ref(null)
  const dialog = ref(false)
  const isEditing = ref(false)
  const saving = ref(false)
  const formRef = ref(null)
  const form = ref({
    id: null,
    code: '',
    name: '',
    description: '',
    isActive: true,
  })

  const headers = [
    { title: 'Code', key: 'code' },
    { title: 'Name', key: 'name' },
    { title: 'Description', key: 'description' },
    { title: 'Status', key: 'isActive' },
    { title: 'Actions', key: 'actions', sortable: false, align: 'end' },
  ]

  const statusOptions = [
    { title: 'Active', value: true },
    { title: 'Inactive', value: false },
  ]

  const filteredDepartments = computed(() => {
    let result = departmentStore.items

    if (search.value) {
      const s = search.value.toLowerCase()
      result = result.filter(d =>
        d.code?.toLowerCase().includes(s)
        || d.name?.toLowerCase().includes(s),
      )
    }

    if (statusFilter.value !== null) {
      result = result.filter(d => d.isActive === statusFilter.value)
    }

    return result
  })

  function openCreateDialog () {
    isEditing.value = false
    form.value = {
      id: null,
      code: '',
      name: '',
      description: '',
      isActive: true,
    }
    dialog.value = true
  }

  function openEditDialog (department) {
    isEditing.value = true
    form.value = {
      id: department.id,
      code: department.code,
      name: department.name,
      description: department.description,
      isActive: department.isActive,
    }
    dialog.value = true
  }

  async function saveDepartment () {
    const { valid } = await formRef.value.validate()
    if (!valid) return

    saving.value = true
    try {
      if (isEditing.value) {
        await departmentStore.updateDepartment(form.value.id, {
          code: form.value.code,
          name: form.value.name,
          description: form.value.description,
          isActive: form.value.isActive,
        })
        notificationStore.showSuccess('Department updated successfully')
      } else {
        await departmentStore.createDepartment(form.value)
        notificationStore.showSuccess('Department created successfully')
      }
      dialog.value = false
      await departmentStore.fetchDepartments()
    } catch (error) {
      notificationStore.showError(error.message || 'Failed to save department')
    } finally {
      saving.value = false
    }
  }

  async function confirmDelete (department) {
    const confirmed = await confirm({
      title: 'Deactivate Department',
      message: `Are you sure you want to deactivate ${department.name}?`,
      icon: 'mdi-office-building-remove',
      color: 'error',
    })

    if (confirmed) {
      try {
        await departmentStore.deleteDepartment(department.id)
        notificationStore.showSuccess('Department deactivated successfully')
        await departmentStore.fetchDepartments()
      } catch {
      // Error toast handled by store
      }
    }
  }

  onMounted(async () => {
    await departmentStore.fetchDepartments()
  })
</script>

// frontend/react/mui/full/src/pages/Departments.tsx
import { useState, useEffect } from 'react'
import {
  Box,
  Card,
  CardContent,
  Button,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  IconButton,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Grid,
} from '@mui/material'
import { Add as AddIcon, Edit as EditIcon, Delete as DeleteIcon } from '@mui/icons-material'
import { useDepartmentStore } from '@/stores'
import { ConfirmDialog } from '@/components'
import type { Department, CreateDepartmentRequest } from '@/types'

export default function Departments() {
  const { departments, loading, fetchDepartments, createDepartment, updateDepartment, deleteDepartment } =
    useDepartmentStore()

  const [dialogOpen, setDialogOpen] = useState(false)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [selectedDepartment, setSelectedDepartment] = useState<Department | null>(null)
  const [formData, setFormData] = useState<CreateDepartmentRequest>({
    name: '',
    code: '',
    description: '',
  })

  useEffect(() => {
    fetchDepartments()
  }, [fetchDepartments])

  const handleOpenCreate = () => {
    setSelectedDepartment(null)
    setFormData({ name: '', code: '', description: '' })
    setDialogOpen(true)
  }

  const handleOpenEdit = (department: Department) => {
    setSelectedDepartment(department)
    setFormData({
      name: department.name,
      code: department.code,
      description: department.description || '',
    })
    setDialogOpen(true)
  }

  const handleOpenDelete = (department: Department) => {
    setSelectedDepartment(department)
    setConfirmOpen(true)
  }

  const handleSubmit = async () => {
    try {
      if (selectedDepartment) {
        await updateDepartment(selectedDepartment.id, formData)
      } else {
        await createDepartment(formData)
      }
      setDialogOpen(false)
      fetchDepartments()
    } catch {
      // Error handled by store
    }
  }

  const handleDelete = async () => {
    if (selectedDepartment) {
      try {
        await deleteDepartment(selectedDepartment.id)
        setConfirmOpen(false)
      } catch {
        // Error toast handled by API interceptor
      }
    }
  }

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'flex-end', mb: 3 }}>
        <Button variant="contained" startIcon={<AddIcon />} onClick={handleOpenCreate}>
          Add Department
        </Button>
      </Box>

      <Card>
        <CardContent>
          <TableContainer>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Name</TableCell>
                  <TableCell>Code</TableCell>
                  <TableCell>Description</TableCell>
                  <TableCell>Status</TableCell>
                  <TableCell align="right">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {(departments || []).map((dept) => (
                  <TableRow key={dept.id}>
                    <TableCell>{dept.name}</TableCell>
                    <TableCell>
                      <Chip label={dept.code} size="small" variant="outlined" />
                    </TableCell>
                    <TableCell>{dept.description || '-'}</TableCell>
                    <TableCell>
                      <Chip
                        label={dept.isActive ? 'Active' : 'Inactive'}
                        color={dept.isActive ? 'success' : 'error'}
                        size="small"
                      />
                    </TableCell>
                    <TableCell align="right">
                      <IconButton size="small" onClick={() => handleOpenEdit(dept)}>
                        <EditIcon />
                      </IconButton>
                      <IconButton
                        size="small"
                        color="error"
                        onClick={() => handleOpenDelete(dept)}
                      >
                        <DeleteIcon />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </CardContent>
      </Card>

      {/* Create/Edit Dialog */}
      <Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} maxWidth="sm" fullWidth>
        <DialogTitle>{selectedDepartment ? 'Edit Department' : 'Create Department'}</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid size={{ xs: 12, sm: 6 }}>
              <TextField
                fullWidth
                label="Name"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              />
            </Grid>
            <Grid size={{ xs: 12, sm: 6 }}>
              <TextField
                fullWidth
                label="Code"
                value={formData.code}
                onChange={(e) => setFormData({ ...formData, code: e.target.value.toUpperCase() })}
              />
            </Grid>
            <Grid size={{ xs: 12 }}>
              <TextField
                fullWidth
                label="Description"
                multiline
                rows={3}
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setDialogOpen(false)}>Cancel</Button>
          <Button variant="contained" onClick={handleSubmit} disabled={loading}>
            {selectedDepartment ? 'Save' : 'Create'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Delete Confirmation */}
      <ConfirmDialog
        open={confirmOpen}
        title="Delete Department"
        message={`Are you sure you want to delete "${selectedDepartment?.name}"?`}
        confirmText="Delete"
        confirmColor="error"
        onConfirm={handleDelete}
        onCancel={() => setConfirmOpen(false)}
      />
    </Box>
  )
}
