// frontend-vuetify/src/pages/departments/index.vue
<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12" class="d-flex justify-space-between align-center">
        <h1 class="text-h4">Departments</h1>
        <v-btn color="primary" prepend-icon="mdi-plus" @click="openCreateDialog">
          Add Department
        </v-btn>
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12" md="6">
        <v-text-field
          v-model="search"
          prepend-inner-icon="mdi-magnify"
          label="Search departments..."
          clearable
          hide-details
          density="compact"
        />
      </v-col>
      <v-col cols="12" md="6">
        <v-select
          v-model="statusFilter"
          :items="statusOptions"
          label="Status"
          clearable
          hide-details
          density="compact"
        />
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12">
        <v-data-table
          :headers="headers"
          :items="filteredDepartments"
          :loading="departmentStore.loading"
          hover
        >
          <template #item.isActive="{ item }">
            <v-chip :color="item.isActive ? 'success' : 'error'" size="small">
              {{ item.isActive ? 'Active' : 'Inactive' }}
            </v-chip>
          </template>
          <template #item.actions="{ item }">
            <v-btn icon="mdi-pencil" variant="text" size="small" @click="openEditDialog(item)" />
            <v-btn icon="mdi-delete" variant="text" size="small" color="error" @click="confirmDelete(item)" />
          </template>
        </v-data-table>
      </v-col>
    </v-row>

    <!-- Create/Edit Dialog -->
    <v-dialog v-model="dialog" max-width="600">
      <v-card>
        <v-card-title>{{ isEditing ? 'Edit Department' : 'Create Department' }}</v-card-title>
        <v-card-text>
          <v-form ref="formRef">
            <v-text-field
              v-model="form.code"
              label="Code"
              :rules="[v => !!v || 'Code is required']"
            />
            <v-text-field
              v-model="form.name"
              label="Name"
              :rules="[v => !!v || 'Name is required']"
            />
            <v-textarea
              v-model="form.description"
              label="Description"
              rows="3"
            />
            <v-switch
              v-if="isEditing"
              v-model="form.isActive"
              label="Active"
              color="success"
            />
          </v-form>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="dialog = false">Cancel</v-btn>
          <v-btn color="primary" :loading="saving" @click="saveDepartment">Save</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { useDepartmentStore } from '@/stores/department'
import { useNotificationStore } from '@/stores/notification'
import { useConfirmDialog } from '@/composables/useConfirmDialog'

const departmentStore = useDepartmentStore()
const notificationStore = useNotificationStore()
const { confirm } = useConfirmDialog()

const search = ref('')
const statusFilter = ref(null)
const dialog = ref(false)
const isEditing = ref(false)
const saving = ref(false)
const formRef = ref(null)
const form = ref({
  id: null,
  code: '',
  name: '',
  description: '',
  isActive: true
})

const headers = [
  { title: 'Code', key: 'code' },
  { title: 'Name', key: 'name' },
  { title: 'Description', key: 'description' },
  { title: 'Status', key: 'isActive' },
  { title: 'Actions', key: 'actions', sortable: false, align: 'end' }
]

const statusOptions = [
  { title: 'Active', value: true },
  { title: 'Inactive', value: false }
]

const filteredDepartments = computed(() => {
  let result = departmentStore.items

  if (search.value) {
    const s = search.value.toLowerCase()
    result = result.filter(d =>
      d.code?.toLowerCase().includes(s) ||
      d.name?.toLowerCase().includes(s)
    )
  }

  if (statusFilter.value !== null) {
    result = result.filter(d => d.isActive === statusFilter.value)
  }

  return result
})

const openCreateDialog = () => {
  isEditing.value = false
  form.value = {
    id: null,
    code: '',
    name: '',
    description: '',
    isActive: true
  }
  dialog.value = true
}

const openEditDialog = (department) => {
  isEditing.value = true
  form.value = {
    id: department.id,
    code: department.code,
    name: department.name,
    description: department.description,
    isActive: department.isActive
  }
  dialog.value = true
}

const saveDepartment = async () => {
  const { valid } = await formRef.value.validate()
  if (!valid) return

  saving.value = true
  try {
    if (isEditing.value) {
      await departmentStore.updateDepartment(form.value.id, {
        code: form.value.code,
        name: form.value.name,
        description: form.value.description,
        isActive: form.value.isActive
      })
      notificationStore.showSuccess('Department updated successfully')
    } else {
      await departmentStore.createDepartment(form.value)
      notificationStore.showSuccess('Department created successfully')
    }
    dialog.value = false
    await departmentStore.fetchDepartments()
  } catch (error) {
    notificationStore.showError(error.message || 'Failed to save department')
  } finally {
    saving.value = false
  }
}

const confirmDelete = async (department) => {
  const confirmed = await confirm({
    title: 'Deactivate Department',
    message: `Are you sure you want to deactivate ${department.name}?`,
    icon: 'mdi-office-building-remove',
    color: 'error'
  })

  if (confirmed) {
    try {
      await departmentStore.deleteDepartment(department.id)
      notificationStore.showSuccess('Department deactivated successfully')
      await departmentStore.fetchDepartments()
    } catch (error) {
      notificationStore.showError(error.message || 'Failed to deactivate department')
    }
  }
}

onMounted(async () => {
  await departmentStore.fetchDepartments()
})
</script>

// frontend-primereact/src/pages/Departments.tsx
import { useState, useEffect, useRef } from 'react'
import { DataTable } from 'primereact/datatable'
import { Column } from 'primereact/column'
import { Button } from 'primereact/button'
import { Dialog } from 'primereact/dialog'
import { InputText } from 'primereact/inputtext'
import { InputTextarea } from 'primereact/inputtextarea'
import { InputSwitch } from 'primereact/inputswitch'
import { Tag } from 'primereact/tag'
import { Toast } from 'primereact/toast'
import { ConfirmDialog } from '@/components'
import { useDepartmentStore } from '@/stores/departmentStore'
import { useNotificationStore } from '@/stores/notificationStore'
import type { Department, CreateDepartmentRequest, UpdateDepartmentRequest } from '@/types/department'

export default function Departments() {
  const toast = useRef<Toast>(null)
  const departments = useDepartmentStore((state) => state.departments)
  const loading = useDepartmentStore((state) => state.loading)
  const fetchDepartments = useDepartmentStore((state) => state.fetchDepartments)
  const createDepartment = useDepartmentStore((state) => state.createDepartment)
  const updateDepartment = useDepartmentStore((state) => state.updateDepartment)
  const deleteDepartment = useDepartmentStore((state) => state.deleteDepartment)

  const showNotification = useNotificationStore((state) => state.showNotification)

  const [dialogVisible, setDialogVisible] = useState(false)
  const [deleteDialogVisible, setDeleteDialogVisible] = useState(false)
  const [selectedDepartment, setSelectedDepartment] = useState<Department | null>(null)
  const [isEditing, setIsEditing] = useState(false)

  const [formData, setFormData] = useState<CreateDepartmentRequest & { isActive: boolean }>({
    name: '',
    code: '',
    description: '',
    isActive: true,
  })

  useEffect(() => {
    fetchDepartments()
  }, [fetchDepartments])

  const openCreateDialog = () => {
    setFormData({
      name: '',
      code: '',
      description: '',
      isActive: true,
    })
    setIsEditing(false)
    setDialogVisible(true)
  }

  const openEditDialog = (department: Department) => {
    setFormData({
      name: department.name,
      code: department.code,
      description: department.description || '',
      isActive: department.isActive,
    })
    setSelectedDepartment(department)
    setIsEditing(true)
    setDialogVisible(true)
  }

  const openDeleteDialog = (department: Department) => {
    setSelectedDepartment(department)
    setDeleteDialogVisible(true)
  }

  const handleSubmit = async () => {
    try {
      if (isEditing && selectedDepartment) {
        const updateData: UpdateDepartmentRequest = {
          name: formData.name,
          description: formData.description,
          isActive: formData.isActive,
        }
        await updateDepartment(selectedDepartment.id, updateData)
        showNotification('Department updated successfully', 'success')
      } else {
        await createDepartment(formData)
        showNotification('Department created successfully', 'success')
      }
      setDialogVisible(false)
    } catch (error: any) {
      showNotification(error.response?.data?.message || 'Operation failed', 'error')
    }
  }

  const handleDelete = async () => {
    if (selectedDepartment) {
      try {
        await deleteDepartment(selectedDepartment.id)
        showNotification('Department deleted successfully', 'success')
        setDeleteDialogVisible(false)
      } catch (error: any) {
        showNotification(error.response?.data?.message || 'Failed to delete department', 'error')
      }
    }
  }

  const statusTemplate = (department: Department) => (
    <Tag
      value={department.isActive ? 'Active' : 'Inactive'}
      severity={department.isActive ? 'success' : 'danger'}
    />
  )

  const actionsTemplate = (department: Department) => (
    <div className="flex gap-2">
      <Button
        icon="pi pi-pencil"
        rounded
        text
        severity="info"
        onClick={() => openEditDialog(department)}
      />
      <Button
        icon="pi pi-trash"
        rounded
        text
        severity="danger"
        onClick={() => openDeleteDialog(department)}
      />
    </div>
  )

  const dialogFooter = (
    <div className="flex justify-content-end gap-2">
      <Button label="Cancel" text onClick={() => setDialogVisible(false)} />
      <Button label={isEditing ? 'Update' : 'Create'} onClick={handleSubmit} />
    </div>
  )

  return (
    <div>
      <Toast ref={toast} />

      <div className="flex justify-content-between align-items-center mb-4">
        <div className="text-3xl font-bold">Departments</div>
        <Button label="Add Department" icon="pi pi-plus" onClick={openCreateDialog} />
      </div>

      <DataTable value={departments} loading={loading} paginator rows={10} stripedRows>
        <Column field="code" header="Code" sortable />
        <Column field="name" header="Name" sortable />
        <Column field="description" header="Description" />
        <Column field="isActive" header="Status" body={statusTemplate} sortable />
        <Column header="Actions" body={actionsTemplate} style={{ width: '120px' }} />
      </DataTable>

      <Dialog
        header={isEditing ? 'Edit Department' : 'Create Department'}
        visible={dialogVisible}
        onHide={() => setDialogVisible(false)}
        footer={dialogFooter}
        style={{ width: '500px' }}
      >
        <div className="flex flex-column gap-4">
          <div>
            <label htmlFor="code" className="block text-900 font-medium mb-2">
              Code
            </label>
            <InputText
              id="code"
              value={formData.code}
              onChange={(e) => setFormData({ ...formData, code: e.target.value })}
              className="w-full"
              disabled={isEditing}
            />
          </div>

          <div>
            <label htmlFor="name" className="block text-900 font-medium mb-2">
              Name
            </label>
            <InputText
              id="name"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full"
            />
          </div>

          <div>
            <label htmlFor="description" className="block text-900 font-medium mb-2">
              Description
            </label>
            <InputTextarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              className="w-full"
              rows={3}
            />
          </div>

          {isEditing && (
            <div className="flex align-items-center gap-2">
              <InputSwitch
                checked={formData.isActive}
                onChange={(e) => setFormData({ ...formData, isActive: e.value ?? false })}
              />
              <label className="text-900 font-medium">Active</label>
            </div>
          )}
        </div>
      </Dialog>

      <ConfirmDialog
        visible={deleteDialogVisible}
        title="Delete Department"
        message={`Are you sure you want to delete department "${selectedDepartment?.name}"?`}
        confirmLabel="Delete"
        confirmSeverity="danger"
        onConfirm={handleDelete}
        onCancel={() => setDeleteDialogVisible(false)}
      />
    </div>
  )
}
