// frontend/vue/primevue/full/src/pages/notifications/index.vue
<template>
  <div class="p-3">
    <div class="flex justify-content-end mb-3">
      <Button
        v-if="unreadCount > 0"
        icon="pi pi-check"
        label="Mark all as read"
        severity="secondary"
        @click="handleMarkAllRead"
      />
    </div>

    <Card>
      <template #content>
        <div v-if="loading" class="flex justify-content-center p-6">
          <ProgressSpinner style="width: 50px; height: 50px" />
        </div>

        <div v-else-if="notifications.length === 0" class="flex flex-column align-items-center justify-content-center p-6 text-center text-500 gap-3">
          <i class="pi pi-inbox text-6xl opacity-50" />
          <span class="text-xl font-medium text-600">No notifications</span>
          <p class="m-0">You're all caught up!</p>
        </div>

        <div v-else class="flex flex-column">
          <div
            v-for="notification in notifications"
            :key="notification.id"
            class="flex align-items-start p-3 border-bottom-1 surface-border hover:surface-hover cursor-pointer transition-colors transition-duration-200"
            :class="{ 'surface-50': !notification.isRead, 'border-left-3 border-primary-500': !notification.isRead }"
            @click="handleMarkAsRead(notification)"
          >
            <div
              class="flex align-items-center justify-content-center border-round w-3rem h-3rem flex-shrink-0"
              :class="{
                'bg-blue-100 text-blue-600': notification.type === 'info',
                'bg-green-100 text-green-600': notification.type === 'success',
                'bg-yellow-100 text-yellow-600': notification.type === 'warning',
                'bg-red-100 text-red-600': notification.type === 'error'
              }"
            >
              <i class="text-xl" :class="getNotificationIcon(notification.type)" />
            </div>

            <div class="flex-1 ml-3">
              <div class="flex justify-content-between align-items-center mb-1">
                <span class="font-bold text-900">{{ notification.title }}</span>
                <span class="text-sm text-500">{{ formatTime(notification.createdAt) }}</span>
              </div>
              <p class="m-0 text-600 line-height-3">{{ notification.message }}</p>
            </div>

            <div v-if="!notification.isRead" class="flex align-items-center ml-3">
              <Button
                v-tooltip.top="'Mark as read'"
                class="text-primary-500 w-2rem h-2rem"
                icon="pi pi-circle-fill"
                rounded
                text
              />
            </div>
          </div>
        </div>
      </template>
    </Card>
  </div>
</template>

<script setup>
  import Button from 'primevue/button'
  import Card from 'primevue/card'
  import ProgressSpinner from 'primevue/progressspinner'
  import { computed, onMounted, ref } from 'vue'
  import { useNotificationStore } from '@/stores/notification'
  import { usePersistentNotificationStore } from '@/stores/persistentNotification'

  const persistentNotificationStore = usePersistentNotificationStore()
  const notificationStore = useNotificationStore()

  const loading = ref(false)

  const notifications = computed(() => persistentNotificationStore.notifications)
  const unreadCount = computed(() => persistentNotificationStore.unreadCount)

  function getNotificationIcon (type) {
    const icons = {
      info: 'pi pi-info-circle',
      success: 'pi pi-check-circle',
      warning: 'pi pi-exclamation-triangle',
      error: 'pi pi-times-circle',
    }
    return icons[type] || 'pi pi-bell'
  }

  function formatTime (dateString) {
    const date = new Date(dateString)
    const now = new Date()
    const diff = now - date

    const minutes = Math.floor(diff / 60_000)
    if (minutes < 1) return 'Just now'
    if (minutes < 60) return `${minutes} minute${minutes > 1 ? 's' : ''} ago`

    const hours = Math.floor(minutes / 60)
    if (hours < 24) return `${hours} hour${hours > 1 ? 's' : ''} ago`

    const days = Math.floor(hours / 24)
    if (days < 7) return `${days} day${days > 1 ? 's' : ''} ago`

    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })
  }

  async function handleMarkAsRead (notification) {
    try {
      await persistentNotificationStore.markAsRead(notification.id)
    } catch {
      notificationStore.error('Failed to mark notification as read')
    }
  }

  async function handleMarkAllRead () {
    try {
      await persistentNotificationStore.markAllAsRead()
      notificationStore.success('All notifications marked as read')
    } catch {
      notificationStore.error('Failed to mark all notifications as read')
    }
  }

  onMounted(async () => {
    loading.value = true
    try {
      await persistentNotificationStore.fetchNotifications()
    } finally {
      loading.value = false
    }
  })
</script>

<style scoped>
/* Scoped styles removed in favor of PrimeFlex utilities */
</style>

// frontend-primereact/src/pages/Notifications.tsx
import { useEffect } from 'react'
import { Card } from 'primereact/card'
import { Button } from 'primereact/button'
import { Tag } from 'primereact/tag'
import { usePersistentNotificationStore } from '@/stores/persistentNotificationStore'
import type { Notification } from '@/types/notification'

export default function Notifications() {
  const notifications = usePersistentNotificationStore((state) => state.notifications)
  const loading = usePersistentNotificationStore((state) => state.loading)
  const unreadCount = usePersistentNotificationStore((state) => state.unreadCount)
  const fetchNotifications = usePersistentNotificationStore((state) => state.fetchNotifications)
  const markAsRead = usePersistentNotificationStore((state) => state.markAsRead)
  const markAllAsRead = usePersistentNotificationStore((state) => state.markAllAsRead)

  useEffect(() => {
    fetchNotifications()
  }, [fetchNotifications])

  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const getSeverityColor = (type: Notification['type']) => {
    const colors: Record<Notification['type'], 'info' | 'success' | 'warning' | 'danger'> = {
      info: 'info',
      success: 'success',
      warning: 'warning',
      error: 'danger',
    }
    return colors[type]
  }

  const getSeverityIcon = (type: Notification['type']) => {
    const icons: Record<Notification['type'], string> = {
      info: 'pi pi-info-circle',
      success: 'pi pi-check-circle',
      warning: 'pi pi-exclamation-triangle',
      error: 'pi pi-times-circle',
    }
    return icons[type]
  }

  return (
    <div>
      <div className="flex justify-content-between align-items-center mb-4">
        <div>
          <div className="text-3xl font-bold">Notifications</div>
          {unreadCount > 0 && (
            <span className="text-500">{unreadCount} unread notification(s)</span>
          )}
        </div>
        {unreadCount > 0 && (
          <Button
            label="Mark All as Read"
            icon="pi pi-check-double"
            outlined
            onClick={() => markAllAsRead()}
          />
        )}
      </div>

      {loading ? (
        <div className="flex justify-content-center py-6">
          <i className="pi pi-spin pi-spinner text-4xl text-500" />
        </div>
      ) : notifications.length === 0 ? (
        <Card>
          <div className="text-center py-6">
            <i className="pi pi-inbox text-6xl text-300 mb-4" />
            <div className="text-xl text-500">No notifications</div>
            <div className="text-500">You're all caught up!</div>
          </div>
        </Card>
      ) : (
        <div className="flex flex-column gap-3">
          {notifications.map((notification) => (
            <Card
              key={notification.id}
              className={notification.isRead ? 'surface-ground' : 'surface-card border-left-3 border-primary'}
            >
              <div className="flex justify-content-between align-items-start">
                <div className="flex gap-3 flex-1">
                  <div
                    className="flex align-items-center justify-content-center border-round flex-shrink-0"
                    style={{
                      width: '2.5rem',
                      height: '2.5rem',
                      backgroundColor: `var(--${getSeverityColor(notification.type)}-100)`,
                    }}
                  >
                    <i
                      className={`${getSeverityIcon(notification.type)} text-${getSeverityColor(notification.type)}-500`}
                    />
                  </div>
                  <div className="flex-1">
                    <div className="flex align-items-center gap-2 mb-1">
                      <span className={`font-${notification.isRead ? 'normal' : 'semibold'} text-900`}>
                        {notification.title}
                      </span>
                      <Tag
                        value={notification.type}
                        severity={getSeverityColor(notification.type)}
                        className="text-xs"
                      />
                    </div>
                    <div className="text-600 mb-2">{notification.message}</div>
                    <div className="text-500 text-sm">{formatDate(notification.createdAt)}</div>
                  </div>
                </div>
                {!notification.isRead && (
                  <Button
                    icon="pi pi-check"
                    rounded
                    text
                    severity="secondary"
                    tooltip="Mark as read"
                    tooltipOptions={{ position: 'left' }}
                    onClick={() => markAsRead(notification.id)}
                  />
                )}
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
