// frontend-vuetify/src/pages/users/index.vue
<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12" class="d-flex justify-space-between align-center">
        <h1 class="text-h4">Users</h1>
        <v-btn color="primary" prepend-icon="mdi-plus" @click="openCreateDialog">
          Add User
        </v-btn>
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12" md="4">
        <v-text-field
          v-model="search"
          prepend-inner-icon="mdi-magnify"
          label="Search users..."
          clearable
          hide-details
          density="compact"
        />
      </v-col>
      <v-col cols="12" md="4">
        <v-select
          v-model="departmentFilter"
          :items="departmentOptions"
          label="Department"
          clearable
          hide-details
          density="compact"
        />
      </v-col>
      <v-col cols="12" md="4">
        <v-select
          v-model="statusFilter"
          :items="statusOptions"
          label="Status"
          clearable
          hide-details
          density="compact"
        />
      </v-col>
    </v-row>

    <v-row>
      <v-col cols="12">
        <v-data-table
          :headers="headers"
          :items="filteredUsers"
          :loading="userStore.loading"
          hover
        >
          <template #item.isActive="{ item }">
            <v-chip :color="item.isActive ? 'success' : 'error'" size="small">
              {{ item.isActive ? 'Active' : 'Inactive' }}
            </v-chip>
          </template>
          <template #item.actions="{ item }">
            <v-btn icon="mdi-pencil" variant="text" size="small" @click="openEditDialog(item)" />
            <v-btn icon="mdi-delete" variant="text" size="small" color="error" @click="confirmDelete(item)" />
          </template>
        </v-data-table>
      </v-col>
    </v-row>

    <!-- Create/Edit Dialog -->
    <v-dialog v-model="dialog" max-width="600">
      <v-card>
        <v-card-title>{{ isEditing ? 'Edit User' : 'Create User' }}</v-card-title>
        <v-card-text>
          <v-form ref="formRef">
            <v-text-field
              v-model="form.username"
              label="Username"
              :disabled="isEditing"
              :rules="[v => !!v || 'Username is required']"
            />
            <v-text-field
              v-model="form.email"
              label="Email"
              type="email"
              :rules="[v => !!v || 'Email is required', v => /.+@.+/.test(v) || 'Invalid email']"
            />
            <v-text-field
              v-if="!isEditing"
              v-model="form.password"
              label="Password"
              type="password"
              :rules="[v => !!v || 'Password is required', v => v.length >= 6 || 'Min 6 characters']"
            />
            <v-row>
              <v-col cols="12" md="6">
                <v-text-field v-model="form.firstName" label="First Name" />
              </v-col>
              <v-col cols="12" md="6">
                <v-text-field v-model="form.lastName" label="Last Name" />
              </v-col>
            </v-row>
            <v-select
              v-model="form.role"
              :items="['Admin', 'User', 'Manager']"
              label="Role"
            />
            <v-select
              v-model="form.departmentId"
              :items="departmentStore.items"
              item-title="name"
              item-value="id"
              label="Department"
              clearable
            />
            <v-switch
              v-if="isEditing"
              v-model="form.isActive"
              label="Active"
              color="success"
            />
          </v-form>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="dialog = false">Cancel</v-btn>
          <v-btn color="primary" :loading="saving" @click="saveUser">Save</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<script setup>
import { useUserStore } from '@/stores/user'
import { useDepartmentStore } from '@/stores/department'
import { useNotificationStore } from '@/stores/notification'
import { useConfirmDialog } from '@/composables/useConfirmDialog'

const userStore = useUserStore()
const departmentStore = useDepartmentStore()
const notificationStore = useNotificationStore()
const { confirm } = useConfirmDialog()

const search = ref('')
const departmentFilter = ref(null)
const statusFilter = ref(null)
const dialog = ref(false)
const isEditing = ref(false)
const saving = ref(false)
const formRef = ref(null)
const form = ref({
  id: null,
  username: '',
  email: '',
  password: '',
  firstName: '',
  lastName: '',
  role: 'User',
  departmentId: null,
  isActive: true
})

const headers = [
  { title: 'Username', key: 'username' },
  { title: 'Username', key: 'username' },
  { title: 'Name', key: 'fullName' },
  { title: 'Email', key: 'email' },
  { title: 'Role', key: 'role' },
  { title: 'Department', key: 'departmentName' },
  { title: 'Status', key: 'isActive' },
  { title: 'Actions', key: 'actions', sortable: false, align: 'end' }
]

const statusOptions = [
  { title: 'Active', value: true },
  { title: 'Inactive', value: false }
]

const departmentOptions = computed(() =>
  departmentStore.items.map(d => ({ title: d.name, value: d.id }))
)

const filteredUsers = computed(() => {
  let result = userStore.items

  if (search.value) {
    const s = search.value.toLowerCase()
    result = result.filter(u =>
      u.username?.toLowerCase().includes(s) ||
      u.firstName?.toLowerCase().includes(s) ||
      u.lastName?.toLowerCase().includes(s) ||
      u.fullName?.toLowerCase().includes(s) ||
      u.email?.toLowerCase().includes(s)
    )
  }

  if (departmentFilter.value) {
    result = result.filter(u => u.departmentId === departmentFilter.value)
  }

  if (statusFilter.value !== null) {
    result = result.filter(u => u.isActive === statusFilter.value)
  }

  return result
})

const openCreateDialog = () => {
  isEditing.value = false
  form.value = {
    id: null,
    username: '',
    email: '',
    password: '',
    firstName: '',
    lastName: '',
    role: 'User',
    departmentId: null,
    isActive: true
  }
  dialog.value = true
}

const openEditDialog = (user) => {
  isEditing.value = true
  form.value = {
    id: user.id,
    username: user.username,
    email: user.email,
    password: '',
    firstName: user.firstName,
    lastName: user.lastName,
    role: user.role,
    departmentId: user.departmentId,
    isActive: user.isActive
  }
  dialog.value = true
}

const saveUser = async () => {
  const { valid } = await formRef.value.validate()
  if (!valid) return

  saving.value = true
  try {
    if (isEditing.value) {
      await userStore.updateUser(form.value.id, {
        email: form.value.email,
        firstName: form.value.firstName,
        lastName: form.value.lastName,
        role: form.value.role,
        departmentId: form.value.departmentId,
        isActive: form.value.isActive
      })
      notificationStore.showSuccess('User updated successfully')
    } else {
      await userStore.createUser(form.value)
      notificationStore.showSuccess('User created successfully')
    }
    dialog.value = false
    await userStore.fetchUsers()
  } catch (error) {
    notificationStore.showError(error.message || 'Failed to save user')
  } finally {
    saving.value = false
  }
}

const confirmDelete = async (user) => {
  const confirmed = await confirm({
    title: 'Deactivate User',
    message: `Are you sure you want to deactivate ${user.username}?`,
    icon: 'mdi-account-off',
    color: 'error'
  })

  if (confirmed) {
    try {
      await userStore.deleteUser(user.id)
      notificationStore.showSuccess('User deactivated successfully')
      await userStore.fetchUsers()
    } catch (error) {
      notificationStore.showError(error.message || 'Failed to deactivate user')
    }
  }
}

onMounted(async () => {
  await Promise.all([
    userStore.fetchUsers(),
    departmentStore.fetchDepartments()
  ])
})
</script>

// frontend-primereact/src/pages/Users.tsx
import { useState, useEffect, useRef } from 'react'
import { DataTable } from 'primereact/datatable'
import { Column } from 'primereact/column'
import { Button } from 'primereact/button'
import { Dialog } from 'primereact/dialog'
import { InputText } from 'primereact/inputtext'
import { Password } from 'primereact/password'
import { Dropdown } from 'primereact/dropdown'
import { Tag } from 'primereact/tag'
import { Toast } from 'primereact/toast'
import { ConfirmDialog } from '@/components'
import { useUserStore } from '@/stores/userStore'
import { useDepartmentStore } from '@/stores/departmentStore'
import { useNotificationStore } from '@/stores/notificationStore'
import type { User, CreateUserRequest, UpdateUserRequest } from '@/types/user'

const roles = [
  { label: 'User', value: 'User' },
  { label: 'Admin', value: 'Admin' },
]

export default function Users() {
  const toast = useRef<Toast>(null)
  const users = useUserStore((state) => state.users)
  const loading = useUserStore((state) => state.loading)
  const fetchUsers = useUserStore((state) => state.fetchUsers)
  const createUser = useUserStore((state) => state.createUser)
  const updateUser = useUserStore((state) => state.updateUser)
  const deleteUser = useUserStore((state) => state.deleteUser)

  const departments = useDepartmentStore((state) => state.departments)
  const fetchDepartments = useDepartmentStore((state) => state.fetchDepartments)

  const showNotification = useNotificationStore((state) => state.showNotification)

  const [dialogVisible, setDialogVisible] = useState(false)
  const [deleteDialogVisible, setDeleteDialogVisible] = useState(false)
  const [selectedUser, setSelectedUser] = useState<User | null>(null)
  const [isEditing, setIsEditing] = useState(false)

  const [formData, setFormData] = useState<CreateUserRequest & { password: string }>({
    username: '',
    email: '',
    password: '',
    firstName: '',
    lastName: '',
    role: 'User',
    departmentId: undefined,
  })

  useEffect(() => {
    fetchUsers()
    fetchDepartments()
  }, [fetchUsers, fetchDepartments])

  const openCreateDialog = () => {
    setFormData({
      username: '',
      email: '',
      password: '',
      firstName: '',
      lastName: '',
      role: 'User',
      departmentId: undefined,
    })
    setIsEditing(false)
    setDialogVisible(true)
  }

  const openEditDialog = (user: User) => {
    setFormData({
      username: user.username,
      email: user.email,
      password: '',
      firstName: user.firstName,
      lastName: user.lastName,
      role: user.role,
      departmentId: user.departmentId,
    })
    setSelectedUser(user)
    setIsEditing(true)
    setDialogVisible(true)
  }

  const openDeleteDialog = (user: User) => {
    setSelectedUser(user)
    setDeleteDialogVisible(true)
  }

  const handleSubmit = async () => {
    try {
      if (isEditing && selectedUser) {
        const updateData: UpdateUserRequest = {
          email: formData.email,
          firstName: formData.firstName,
          lastName: formData.lastName,
          role: formData.role,
          departmentId: formData.departmentId,
        }
        await updateUser(selectedUser.id, updateData)
        showNotification('User updated successfully', 'success')
      } else {
        await createUser(formData)
        showNotification('User created successfully', 'success')
      }
      setDialogVisible(false)
    } catch (error: any) {
      showNotification(error.response?.data?.message || 'Operation failed', 'error')
    }
  }

  const handleDelete = async () => {
    if (selectedUser) {
      try {
        await deleteUser(selectedUser.id)
        showNotification('User deleted successfully', 'success')
        setDeleteDialogVisible(false)
      } catch (error: any) {
        showNotification(error.response?.data?.message || 'Failed to delete user', 'error')
      }
    }
  }

  const statusTemplate = (user: User) => (
    <Tag value={user.isActive ? 'Active' : 'Inactive'} severity={user.isActive ? 'success' : 'danger'} />
  )

  const roleTemplate = (user: User) => (
    <Tag value={user.role} severity={user.role === 'Admin' ? 'warning' : 'info'} />
  )

  const actionsTemplate = (user: User) => (
    <div className="flex gap-2">
      <Button icon="pi pi-pencil" rounded text severity="info" onClick={() => openEditDialog(user)} />
      <Button icon="pi pi-trash" rounded text severity="danger" onClick={() => openDeleteDialog(user)} />
    </div>
  )

  const departmentOptions = departments.map((d) => ({ label: d.name, value: d.id }))

  const dialogFooter = (
    <div className="flex justify-content-end gap-2">
      <Button label="Cancel" text onClick={() => setDialogVisible(false)} />
      <Button label={isEditing ? 'Update' : 'Create'} onClick={handleSubmit} />
    </div>
  )

  return (
    <div>
      <Toast ref={toast} />

      <div className="flex justify-content-between align-items-center mb-4">
        <div className="text-3xl font-bold">Users</div>
        <Button label="Add User" icon="pi pi-plus" onClick={openCreateDialog} />
      </div>

      <DataTable value={users} loading={loading} paginator rows={10} stripedRows>
        <Column field="username" header="Username" sortable />
        <Column field="email" header="Email" sortable />
        <Column field="firstName" header="First Name" sortable />
        <Column field="lastName" header="Last Name" sortable />
        <Column field="departmentName" header="Department" sortable />
        <Column field="role" header="Role" body={roleTemplate} sortable />
        <Column field="isActive" header="Status" body={statusTemplate} sortable />
        <Column header="Actions" body={actionsTemplate} style={{ width: '120px' }} />
      </DataTable>

      <Dialog
        header={isEditing ? 'Edit User' : 'Create User'}
        visible={dialogVisible}
        onHide={() => setDialogVisible(false)}
        footer={dialogFooter}
        style={{ width: '500px' }}
      >
        <div className="flex flex-column gap-4">
          <div>
            <label htmlFor="username" className="block text-900 font-medium mb-2">
              Username
            </label>
            <InputText
              id="username"
              value={formData.username}
              onChange={(e) => setFormData({ ...formData, username: e.target.value })}
              className="w-full"
              disabled={isEditing}
            />
          </div>

          <div>
            <label htmlFor="email" className="block text-900 font-medium mb-2">
              Email
            </label>
            <InputText
              id="email"
              type="email"
              value={formData.email}
              onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              className="w-full"
            />
          </div>

          {!isEditing && (
            <div>
              <label htmlFor="password" className="block text-900 font-medium mb-2">
                Password
              </label>
              <Password
                id="password"
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                className="w-full"
                inputClassName="w-full"
                toggleMask
              />
            </div>
          )}

          <div className="grid">
            <div className="col-6">
              <label htmlFor="firstName" className="block text-900 font-medium mb-2">
                First Name
              </label>
              <InputText
                id="firstName"
                value={formData.firstName}
                onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                className="w-full"
              />
            </div>
            <div className="col-6">
              <label htmlFor="lastName" className="block text-900 font-medium mb-2">
                Last Name
              </label>
              <InputText
                id="lastName"
                value={formData.lastName}
                onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
                className="w-full"
              />
            </div>
          </div>

          <div>
            <label htmlFor="role" className="block text-900 font-medium mb-2">
              Role
            </label>
            <Dropdown
              id="role"
              value={formData.role}
              options={roles}
              onChange={(e) => setFormData({ ...formData, role: e.value })}
              className="w-full"
            />
          </div>

          <div>
            <label htmlFor="department" className="block text-900 font-medium mb-2">
              Department
            </label>
            <Dropdown
              id="department"
              value={formData.departmentId}
              options={departmentOptions}
              onChange={(e) => setFormData({ ...formData, departmentId: e.value })}
              className="w-full"
              placeholder="Select a department"
              showClear
            />
          </div>
        </div>
      </Dialog>

      <ConfirmDialog
        visible={deleteDialogVisible}
        title="Delete User"
        message={`Are you sure you want to delete user "${selectedUser?.username}"?`}
        confirmLabel="Delete"
        confirmSeverity="danger"
        onConfirm={handleDelete}
        onCancel={() => setDeleteDialogVisible(false)}
      />
    </div>
  )
}
