// frontend/react/primereact/full/src/components/layout/Breadcrumbs.tsx
import { useMemo } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { BreadCrumb } from 'primereact/breadcrumb'
import { MenuItem } from 'primereact/menuitem'

function formatLabel(segment: string): string {
  return segment
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

export function Breadcrumbs() {
  const location = useLocation()
  const navigate = useNavigate()

  const home: MenuItem = {
    icon: 'pi pi-home',
    command: () => navigate('/'),
  }

  const breadcrumbs: MenuItem[] = useMemo(() => {
    const paths = location.pathname.split('/').filter(Boolean)

    return paths.map((segment, index) => {
      const path = '/' + paths.slice(0, index + 1).join('/')
      const isLast = index === paths.length - 1

      return {
        label: formatLabel(segment),
        command: isLast ? undefined : () => navigate(path),
        disabled: isLast,
      }
    })
  }, [location.pathname, navigate])

  // Don't show breadcrumbs on home page
  if (location.pathname === '/') {
    return null
  }

  return (
    <div className="mb-3">
      <BreadCrumb model={breadcrumbs} home={home} className="surface-card border-round" />
    </div>
  )
}

// frontend-vuetify/src/components/layout/Breadcrumbs.vue
<template>
  <v-breadcrumbs :items="breadcrumbs" class="px-0 py-2">
    <template #prepend>
      <v-icon icon="mdi-home" size="small" class="me-1" />
    </template>
    <template #divider>
      <v-icon icon="mdi-chevron-right" size="small" />
    </template>
  </v-breadcrumbs>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()

const formatLabel = (segment) => {
  return segment
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

const breadcrumbs = computed(() => {
  const paths = route.path.split('/').filter(Boolean)

  // Start with Home
  const items = [
    {
      title: 'Home',
      to: '/',
      disabled: false,
    },
  ]

  // Build breadcrumb trail
  paths.forEach((segment, index) => {
    const path = '/' + paths.slice(0, index + 1).join('/')
    const isLast = index === paths.length - 1

    items.push({
      title: formatLabel(segment),
      to: path,
      disabled: isLast,
    })
  })

  return items
})
</script>
