// frontend/vue/vuetify/minimal/src/components/AppHeader.vue
<template>
  <v-app-bar class="app-header" color="surface" elevation="0" height="64">
    <!-- Menu Toggle Button -->
    <v-app-bar-nav-icon
      class="ml-1"
      @click="$emit('toggle-sidebar')"
    >
      <v-icon>mdi-menu</v-icon>
    </v-app-bar-nav-icon>

    <!-- Page Title -->
    <v-app-bar-title class="ml-2 mobile-title-wrap">
      <h2
        class="font-weight-bold"
        :class="display.smAndDown.value ? 'text-subtitle-1 text-wrap' : 'text-h5'"
        :style="display.smAndDown.value ? 'line-height: 1.2' : ''"
      >
        {{ pageTitle }}
      </h2>
    </v-app-bar-title>

    <v-spacer />

    <!-- Page Actions Slot -->
    <div v-if="$slots.actions" class="mr-2">
      <slot name="actions" />
    </div>

    <!-- Action Buttons -->
    <div class="d-flex align-center mr-2">
      <!-- Language Switcher -->
      <v-menu offset-y>
        <template #activator="{ props }">
          <v-btn
            v-bind="props"
            icon
            size="small"
            variant="text"
          >
            <v-icon>mdi-translate</v-icon>
          </v-btn>
        </template>
        <v-list density="compact" min-width="160" nav>
          <v-list-item
            v-for="lang in localeStore.availableLocales"
            :key="lang.code"
            :active="localeStore.locale === lang.code"
            @click="localeStore.setLocale(lang.code)"
          >
            <template #prepend>
              <span class="mr-2">{{ lang.flag }}</span>
            </template>
            <v-list-item-title>{{ lang.name }}</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>

      <!-- Theme Toggle -->
      <v-menu offset-y>
        <template #activator="{ props }">
          <v-btn
            v-bind="props"
            icon
            size="small"
            variant="text"
          >
            <v-icon>{{ themeIcon }}</v-icon>
          </v-btn>
        </template>
        <v-list density="compact" min-width="160" nav>
          <v-list-item
            v-for="option in themeOptions"
            :key="option.value"
            :active="themeStore.themeMode === option.value"
            :prepend-icon="option.icon"
            @click="themeStore.setTheme(option.value)"
          >
            <v-list-item-title>{{ option.label }}</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>

      <!-- Notifications -->
      <NotificationMenu />

      <!-- User Menu -->
      <v-menu offset-y>
        <template #activator="{ props }">
          <v-btn
            class="user-menu-btn ml-2"
            v-bind="props"
            variant="text"
          >
            <v-avatar size="36">
              <v-img
                :alt="userName"
                :src="userAvatarUrl"
              />
            </v-avatar>
            <span class="ml-2 d-none d-sm-inline text-body-2">{{ userName }}</span>
            <v-icon class="ml-1 d-none d-sm-inline" size="small">mdi-chevron-down</v-icon>
          </v-btn>
        </template>

        <v-card class="user-menu-card" min-width="240">
          <!-- User Info -->
          <v-card-text class="pa-4">
            <div class="d-flex align-center mb-3">
              <v-avatar size="48">
                <v-img
                  :alt="userName"
                  :src="userAvatarUrl"
                />
              </v-avatar>
              <div class="ml-3">
                <p class="text-body-2 font-weight-medium mb-0">{{ userName }}</p>
                <p class="text-caption text-medium-emphasis mb-0">{{ userDepartment }}</p>
              </div>
            </div>
          </v-card-text>

          <v-divider />

          <!-- Menu Items -->
          <v-list density="compact" nav>
            <v-list-item
              v-for="item in userMenuItems"
              :key="item.title"
              :prepend-icon="item.icon"
              :to="item.to"
              @click="item.action"
            >
              <v-list-item-title>{{ item.title }}</v-list-item-title>
            </v-list-item>
          </v-list>
        </v-card>
      </v-menu>
    </div>
  </v-app-bar>
</template>

<script setup>
  import { storeToRefs } from 'pinia'
  import { computed, ref } from 'vue'
  import { useRoute } from 'vue-router'
  import { useDisplay } from 'vuetify'
  import NotificationMenu from '@/components/common/NotificationMenu.vue'
  import { useConfirmDialog } from '@/composables/useConfirmDialog'
  import { useAuthStore } from '@/stores/auth'
  import { useLocaleStore } from '@/stores/locale'
  import { useThemeStore } from '@/stores/theme'

  defineEmits(['toggle-sidebar'])

  const route = useRoute()
  const display = useDisplay()
  const confirmDialog = useConfirmDialog()
  const authStore = useAuthStore()
  const themeStore = useThemeStore()
  const localeStore = useLocaleStore()
  const { user } = storeToRefs(authStore)

  const themeOptions = [
    { value: 'light', label: 'Light', icon: 'mdi-white-balance-sunny' },
    { value: 'dark', label: 'Dark', icon: 'mdi-weather-night' },
    { value: 'system', label: 'System', icon: 'mdi-laptop' },
  ]

  const themeIcon = computed(() => {
    const icons = {
      light: 'mdi-white-balance-sunny',
      dark: 'mdi-weather-night',
      system: 'mdi-laptop',
    }
    return icons[themeStore.themeMode] || 'mdi-laptop'
  })

  const pageTitle = computed(() => {
    // Get title from route meta or generate from route name
    if (route.meta.title) {
      return route.meta.title
    }

    // Generate title from route path
    const pathSegments = route.path.split('/').filter(Boolean)

    if (pathSegments.length === 0) {
      return 'Notifications'
    }

    // Handle detail pages with [id]
    if (route.params.id) {
      const basePath = pathSegments[0]
      return getTitleFromPath(basePath) + ' Detail'
    }

    // Handle form pages
    if (pathSegments.at(-1) === 'form') {
      const basePath = pathSegments[0]
      return route.query.id ? 'Edit ' + getTitleFromPath(basePath) : 'New ' + getTitleFromPath(basePath)
    }

    // Default: use first segment
    return getTitleFromPath(pathSegments[0])
  })

  function getTitleFromPath (path) {
    const titles = {
      'notifications': 'Notifications',
      'files': 'Files',
      'audit-logs': 'Audit Logs',
      'profile': 'Profile',
    }
    return titles[path] || path.charAt(0).toUpperCase() + path.slice(1).replace(/-/g, ' ')
  }

  const userMenuItems = ref([
    { title: 'Profile', icon: 'mdi-account', to: '/profile' },
    { title: 'Logout', icon: 'mdi-logout', action: handleLogout },
  ])

  const userName = computed(() => user.value?.name || user.value?.username || 'User')
  const userDepartment = computed(() => user.value?.department || 'No Department')

  const userAvatarUrl = computed(() => {
    return `https://ui-avatars.com/api/?name=${encodeURIComponent(userName.value)}&background=1976d2&color=fff`
  })

  async function handleLogout () {
    const confirmed = await confirmDialog.confirm({
      title: 'Sign Out',
      message: `Are you sure you want to sign out?\n\n• User: ${userName.value}\n• Department: ${userDepartment.value}\n\nYou will be redirected to the login page.`,
      icon: 'mdi-logout',
      color: 'warning',
      confirmLabel: 'Sign Out',
      cancelLabel: 'Stay Logged In',
    })

    if (confirmed) {
      await authStore.logout()
    }
  }
</script>

<style scoped>
.app-header {
  border-bottom: 1px solid rgba(var(--v-border-color), var(--v-border-opacity));
}

.user-menu-btn {
  border-radius: 50px;
  text-transform: none;
}

.user-menu-card {
  margin-top: 8px;
}

:deep(.mobile-title-wrap .v-app-bar-title__content) {
  text-overflow: clip;
  white-space: normal;
  overflow: visible;
}
</style>

// frontend/react/mui/minimal/src/components/layout/AppHeader.tsx
import { useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import {
  AppBar,
  Toolbar,
  IconButton,
  Typography,
  Box,
  Avatar,
  Menu,
  MenuItem,
  ListItemIcon,
  Divider,
} from '@mui/material'
import {
  Menu as MenuIcon,
  Person as PersonIcon,
  Logout as LogoutIcon,
  LightMode as LightModeIcon,
  DarkMode as DarkModeIcon,
  Computer as ComputerIcon,
  Translate as TranslateIcon,
} from '@mui/icons-material'
import { useAuthStore, useThemeStore, ThemeMode } from '@/stores'
import { useLocaleStore } from '@/stores/localeStore'
import { NotificationMenu } from '@/components/common/NotificationMenu'
import { ConfirmDialog } from '@/components'

interface AppHeaderProps {
  onToggleSidebar: () => void
}

const pageTitles: Record<string, string> = {
  '/profile': 'Profile',
  '/notifications': 'Notifications',
  '/files': 'Files',
  '/audit-logs': 'Audit Logs',
}

export function AppHeader({ onToggleSidebar }: AppHeaderProps) {
  const navigate = useNavigate()
  const location = useLocation()
  const user = useAuthStore((state) => state.user)
  const logout = useAuthStore((state) => state.logout)
  const themeMode = useThemeStore((state) => state.themeMode)
  const setTheme = useThemeStore((state) => state.setTheme)
  const locale = useLocaleStore((state) => state.locale)
  const availableLocales = useLocaleStore((state) => state.availableLocales)
  const setLocale = useLocaleStore((state) => state.setLocale)
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null)
  const [themeAnchorEl, setThemeAnchorEl] = useState<null | HTMLElement>(null)
  const [langAnchorEl, setLangAnchorEl] = useState<null | HTMLElement>(null)
  const [logoutDialogOpen, setLogoutDialogOpen] = useState(false)

  const themeOptions: { mode: ThemeMode; label: string; icon: React.ReactNode }[] = [
    { mode: 'light', label: 'Light', icon: <LightModeIcon fontSize="small" /> },
    { mode: 'dark', label: 'Dark', icon: <DarkModeIcon fontSize="small" /> },
    { mode: 'system', label: 'System', icon: <ComputerIcon fontSize="small" /> },
  ]

  const getCurrentThemeIcon = () => {
    switch (themeMode) {
      case 'light':
        return <LightModeIcon />
      case 'dark':
        return <DarkModeIcon />
      default:
        return <ComputerIcon />
    }
  }

  const handleThemeMenuOpen = (event: React.MouseEvent<HTMLElement>) => {
    setThemeAnchorEl(event.currentTarget)
  }

  const handleThemeMenuClose = () => {
    setThemeAnchorEl(null)
  }

  const handleThemeChange = (mode: ThemeMode) => {
    setTheme(mode)
    handleThemeMenuClose()
  }

  const handleLangMenuOpen = (event: React.MouseEvent<HTMLElement>) => {
    setLangAnchorEl(event.currentTarget)
  }

  const handleLangMenuClose = () => {
    setLangAnchorEl(null)
  }

  const handleLangChange = (code: string) => {
    setLocale(code)
    handleLangMenuClose()
  }

  const pageTitle = pageTitles[location.pathname] || 'AppTemplate'

  const handleMenuOpen = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget)
  }

  const handleMenuClose = () => {
    setAnchorEl(null)
  }

  const handleProfile = () => {
    handleMenuClose()
    navigate('/profile')
  }

  const handleLogoutClick = () => {
    handleMenuClose()
    setLogoutDialogOpen(true)
  }

  const handleLogoutConfirm = async () => {
    setLogoutDialogOpen(false)
    await logout()
    navigate('/login')
  }

  const handleLogoutCancel = () => {
    setLogoutDialogOpen(false)
  }

  const getInitials = () => {
    if (user?.firstName && user?.lastName) {
      return `${user.firstName[0]}${user.lastName[0]}`.toUpperCase()
    }
    return user?.username?.[0]?.toUpperCase() || 'U'
  }

  return (
    <AppBar
      position="sticky"
      color="inherit"
      elevation={1}
      sx={{ backgroundColor: 'background.paper' }}
    >
      <Toolbar>
        <IconButton
          edge="start"
          color="inherit"
          aria-label="menu"
          onClick={onToggleSidebar}
          sx={{ mr: 2 }}
        >
          <MenuIcon />
        </IconButton>

        <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
          {pageTitle}
        </Typography>

        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          {/* Language Switcher */}
          <IconButton onClick={handleLangMenuOpen} size="small">
            <TranslateIcon />
          </IconButton>
          <Menu
            anchorEl={langAnchorEl}
            open={Boolean(langAnchorEl)}
            onClose={handleLangMenuClose}
            transformOrigin={{ horizontal: 'right', vertical: 'top' }}
            anchorOrigin={{ horizontal: 'right', vertical: 'bottom' }}
          >
            {availableLocales.map((lang) => (
              <MenuItem
                key={lang.code}
                onClick={() => handleLangChange(lang.code)}
                selected={locale === lang.code}
              >
                <ListItemIcon>{lang.flag}</ListItemIcon>
                {lang.name}
              </MenuItem>
            ))}
          </Menu>

          {/* Theme Toggle */}
          <IconButton onClick={handleThemeMenuOpen} size="small">
            {getCurrentThemeIcon()}
          </IconButton>
          <Menu
            anchorEl={themeAnchorEl}
            open={Boolean(themeAnchorEl)}
            onClose={handleThemeMenuClose}
            transformOrigin={{ horizontal: 'right', vertical: 'top' }}
            anchorOrigin={{ horizontal: 'right', vertical: 'bottom' }}
          >
            {themeOptions.map((option) => (
              <MenuItem
                key={option.mode}
                onClick={() => handleThemeChange(option.mode)}
                selected={themeMode === option.mode}
              >
                <ListItemIcon>{option.icon}</ListItemIcon>
                {option.label}
              </MenuItem>
            ))}
          </Menu>

          <NotificationMenu />

          <IconButton onClick={handleMenuOpen} size="small">
            <Avatar sx={{ width: 36, height: 36, bgcolor: 'primary.main' }}>
              {getInitials()}
            </Avatar>
          </IconButton>

          <Menu
            anchorEl={anchorEl}
            open={Boolean(anchorEl)}
            onClose={handleMenuClose}
            transformOrigin={{ horizontal: 'right', vertical: 'top' }}
            anchorOrigin={{ horizontal: 'right', vertical: 'bottom' }}
          >
            <Box sx={{ px: 2, py: 1 }}>
              <Typography variant="subtitle1" fontWeight="bold">
                {user?.firstName} {user?.lastName}
              </Typography>
              <Typography variant="body2" color="text.secondary">
                {user?.email}
              </Typography>
            </Box>
            <Divider />
            <MenuItem onClick={handleProfile}>
              <ListItemIcon>
                <PersonIcon fontSize="small" />
              </ListItemIcon>
              Profile
            </MenuItem>
            <MenuItem onClick={handleLogoutClick}>
              <ListItemIcon>
                <LogoutIcon fontSize="small" />
              </ListItemIcon>
              Logout
            </MenuItem>
          </Menu>
        </Box>
      </Toolbar>

      <ConfirmDialog
        open={logoutDialogOpen}
        title="Sign Out"
        message={`Are you sure you want to sign out?\n\nYou will be redirected to the login page.`}
        confirmText="Sign Out"
        cancelText="Stay Logged In"
        confirmColor="warning"
        onConfirm={handleLogoutConfirm}
        onCancel={handleLogoutCancel}
      />
    </AppBar>
  )
}
