// frontend/react/primereact/minimal/src/components/layout/AppHeader.tsx
import { useRef, useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { Button } from 'primereact/button'
import { Avatar } from 'primereact/avatar'
import { Menu } from 'primereact/menu'
import { useAuthStore, useThemeStore, useLocaleStore } from '@/stores'
import { NotificationMenu } from '@/components/common/NotificationMenu'
import { ConfirmDialog } from '@/components'

interface AppHeaderProps {
  onToggleSidebar: () => void
}

const pageTitles: Record<string, string> = {
  '/profile': 'Profile',
  '/notifications': 'Notifications',
  '/files': 'Files',
  '/audit-logs': 'Audit Logs',
}

export function AppHeader({ onToggleSidebar }: AppHeaderProps) {
  const navigate = useNavigate()
  const location = useLocation()
  const user = useAuthStore((state) => state.user)
  const logout = useAuthStore((state) => state.logout)
  const themeMode = useThemeStore((state) => state.themeMode)
  const setTheme = useThemeStore((state) => state.setTheme)
  const locale = useLocaleStore((state) => state.locale)
  const setLocale = useLocaleStore((state) => state.setLocale)
  const availableLocales = useLocaleStore((state) => state.availableLocales)
  const menu = useRef<Menu>(null)
  const themeMenu = useRef<Menu>(null)
  const langMenu = useRef<Menu>(null)
  const [logoutDialogVisible, setLogoutDialogVisible] = useState(false)

  const getThemeIcon = () => {
    switch (themeMode) {
      case 'light':
        return 'pi pi-sun'
      case 'dark':
        return 'pi pi-moon'
      default:
        return 'pi pi-desktop'
    }
  }

  const themeMenuItems = [
    {
      label: 'Light',
      icon: 'pi pi-sun',
      command: () => setTheme('light'),
    },
    {
      label: 'Dark',
      icon: 'pi pi-moon',
      command: () => setTheme('dark'),
    },
    {
      label: 'System',
      icon: 'pi pi-desktop',
      command: () => setTheme('system'),
    },
  ]

  const langMenuItems = availableLocales.map((loc) => ({
    label: `${loc.flag} ${loc.name}`,
    command: () => setLocale(loc.code),
  }))

  const currentLocaleFlag = availableLocales.find((l) => l.code === locale)?.flag || '🌐'

  const pageTitle = pageTitles[location.pathname] || 'AppTemplate'

  const handleLogoutClick = () => {
    setLogoutDialogVisible(true)
  }

  const handleLogoutConfirm = async () => {
    setLogoutDialogVisible(false)
    await logout()
    navigate('/login')
  }

  const handleLogoutCancel = () => {
    setLogoutDialogVisible(false)
  }

  const getInitials = () => {
    if (user?.name) {
      return user.name
        .split(' ')
        .map((n) => n[0])
        .join('')
        .toUpperCase()
        .substring(0, 2)
    }
    return user?.username?.[0]?.toUpperCase() || 'U'
  }

  const menuItems = [
    {
      label: user?.name || user?.username,
      disabled: true,
      style: { opacity: 1, fontWeight: 'bold' },
    },
    { separator: true },
    {
      label: 'Profile',
      icon: 'pi pi-user',
      command: () => navigate('/profile'),
    },
    {
      label: 'Logout',
      icon: 'pi pi-sign-out',
      command: handleLogoutClick,
    },
  ]

  return (
    <>
      <header
        className="flex align-items-center justify-content-between px-4 py-3 surface-card shadow-1"
        style={{ position: 'sticky', top: 0, zIndex: 100, borderBottom: '1px solid var(--surface-border)' }}
      >
        <div className="flex align-items-center gap-3">
          <Button
            icon="pi pi-bars"
            text
            onClick={onToggleSidebar}
            className="p-button-text"
          />
          <span className="text-xl font-semibold">{pageTitle}</span>
        </div>

        <div className="flex align-items-center gap-2">
          {/* Language Switcher */}
          <Menu model={langMenuItems} popup ref={langMenu} />
          <Button
            text
            rounded
            onClick={(e) => langMenu.current?.toggle(e)}
            className="p-button-text"
          >
            <span style={{ fontSize: '1.25rem' }}>{currentLocaleFlag}</span>
          </Button>

          {/* Theme Toggle */}
          <Menu model={themeMenuItems} popup ref={themeMenu} />
          <Button
            icon={getThemeIcon()}
            text
            rounded
            onClick={(e) => themeMenu.current?.toggle(e)}
            className="p-button-text"
          />

          <NotificationMenu />

          <Menu model={menuItems} popup ref={menu} />
          <Button
            className="p-button-text"
            onClick={(e) => menu.current?.toggle(e)}
          >
            <Avatar label={getInitials()} shape="circle" className="bg-primary" />
          </Button>
        </div>
      </header>

      <ConfirmDialog
        visible={logoutDialogVisible}
        title="Sign Out"
        message="Are you sure you want to sign out? You will be redirected to the login page."
        confirmLabel="Sign Out"
        cancelLabel="Stay Logged In"
        confirmSeverity="warning"
        onConfirm={handleLogoutConfirm}
        onCancel={handleLogoutCancel}
      />
    </>
  )
}

// frontend/vue/primevue/minimal/src/components/AppHeader.vue
<template>
  <header class="app-header">
    <div class="header-left">
      <Button
        class="menu-button"
        icon="pi pi-bars"
        rounded
        severity="secondary"
        text
        @click="$emit('toggle-sidebar')"
      />
      <Breadcrumbs />
    </div>

    <div class="header-right">
      <!-- Language Switcher -->
      <Button
        class="lang-button"
        icon="pi pi-globe"
        rounded
        severity="secondary"
        text
        type="button"
        @click="toggleLangMenu"
      />
      <Menu ref="langMenu" :model="langMenuItems" :popup="true" />

      <!-- Theme Toggle -->
      <Button
        class="theme-button"
        :icon="themeIcon"
        rounded
        severity="secondary"
        text
        type="button"
        @click="toggleThemeMenu"
      />
      <Menu ref="themeMenu" :model="themeMenuItems" :popup="true" />

      <!-- Notifications -->
      <NotificationMenu />

      <!-- User Menu -->
      <Button
        class="user-button"
        rounded
        text
        type="button"
        @click="toggleUserMenu"
      >
        <Avatar
          class="user-avatar"
          :label="userInitials"
          shape="circle"
        />
        <span class="user-name">{{ userName }}</span>
        <i class="pi pi-chevron-down" style="font-size: 0.75rem" />
      </Button>
      <Menu ref="userMenu" :model="userMenuItems" :popup="true" />
    </div>
  </header>
</template>

<script setup>
  import Avatar from 'primevue/avatar'
  import Button from 'primevue/button'
  import Menu from 'primevue/menu'
  import { computed, ref } from 'vue'
  import { useRoute, useRouter } from 'vue-router'
  import NotificationMenu from '@/components/common/NotificationMenu.vue'
  import Breadcrumbs from '@/components/layout/Breadcrumbs.vue'
  import { useAuthStore } from '@/stores/auth'
  import { useLocaleStore } from '@/stores/locale'
  import { useThemeStore } from '@/stores/theme'

  defineEmits(['toggle-sidebar'])

  const router = useRouter()
  const route = useRoute()
  const authStore = useAuthStore()
  const themeStore = useThemeStore()
  const localeStore = useLocaleStore()
  const userMenu = ref()
  const themeMenu = ref()
  const langMenu = ref()

  const themeIcon = computed(() => {
    const icons = {
      light: 'pi pi-sun',
      dark: 'pi pi-moon',
      system: 'pi pi-desktop',
    }
    return icons[themeStore.themeMode] || 'pi pi-desktop'
  })

  const themeMenuItems = ref([
    {
      label: 'Light',
      icon: 'pi pi-sun',
      command: () => themeStore.setTheme('light'),
    },
    {
      label: 'Dark',
      icon: 'pi pi-moon',
      command: () => themeStore.setTheme('dark'),
    },
    {
      label: 'System',
      icon: 'pi pi-desktop',
      command: () => themeStore.setTheme('system'),
    },
  ])

  function toggleThemeMenu (event) {
    themeMenu.value.toggle(event)
  }

  const langMenuItems = computed(() =>
    localeStore.availableLocales.map(lang => ({
      label: lang.name,
      icon: localeStore.locale === lang.code ? 'pi pi-check' : '',
      command: () => localeStore.setLocale(lang.code),
    })),
  )

  function toggleLangMenu (event) {
    langMenu.value.toggle(event)
  }

  const userName = computed(() => authStore.user?.name || authStore.user?.username || 'User')
  const userInitials = computed(() => {
    const name = userName.value
    return name
      .split(' ')
      .map(n => n[0])
      .join('')
      .toUpperCase()
      .slice(0, 2)
  })

  const userMenuItems = ref([
    {
      label: 'Profile',
      icon: 'pi pi-user',
      command: () => router.push('/profile'),
    },
    {
      separator: true,
    },
    {
      label: 'Logout',
      icon: 'pi pi-sign-out',
      command: () => handleLogout(),
    },
  ])

  function toggleUserMenu (event) {
    userMenu.value.toggle(event)
  }

  async function handleLogout () {
    await authStore.logout()
    router.push('/login')
  }
</script>

<style scoped>
.app-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem 1.5rem;
  background-color: var(--p-surface-card);
  border-bottom: 1px solid var(--p-surface-border);
  position: sticky;
  top: 0;
  z-index: 1000;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.page-title {
  font-size: 1.25rem;
  font-weight: 600;
  color: var(--p-text-color);
}

.header-right {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.user-button {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem;
}

.user-avatar {
  background-color: var(--p-primary-color);
  color: var(--p-primary-contrast-color);
}

.user-name {
  font-weight: 500;
  color: var(--p-text-color);
}

@media (max-width: 768px) {
  .user-name {
    display: none;
  }

  .app-title {
    font-size: 1rem;
  }
}
</style>
