// frontend/react/primereact/full/src/components/layout/Breadcrumbs.tsx
import { useMemo } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { BreadCrumb } from 'primereact/breadcrumb'
import { MenuItem } from 'primereact/menuitem'

function formatLabel(segment: string): string {
  return segment
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

export function Breadcrumbs() {
  const location = useLocation()
  const navigate = useNavigate()

  const home: MenuItem = {
    icon: 'pi pi-home',
    command: () => navigate('/'),
  }

  const breadcrumbs: MenuItem[] = useMemo(() => {
    const paths = location.pathname.split('/').filter(Boolean)

    return paths.map((segment, index) => {
      const path = '/' + paths.slice(0, index + 1).join('/')
      const isLast = index === paths.length - 1

      return {
        label: formatLabel(segment),
        command: isLast ? undefined : () => navigate(path),
        disabled: isLast,
      }
    })
  }, [location.pathname, navigate])

  // Don't show breadcrumbs on home page
  if (location.pathname === '/') {
    return null
  }

  return (
    <div className="mb-3">
      <BreadCrumb model={breadcrumbs} home={home} className="surface-card border-round" />
    </div>
  )
}

// frontend-primevue/src/components/layout/Breadcrumbs.vue
<template>
  <Breadcrumb :home="home" :model="breadcrumbs" class="mb-3 surface-card border-round">
    <template #item="{ item }">
      <router-link v-if="item.route" :to="item.route" class="text-color no-underline">
        <span :class="item.icon" class="mr-1" />
        <span>{{ item.label }}</span>
      </router-link>
      <span v-else class="text-color-secondary">
        <span :class="item.icon" class="mr-1" />
        <span>{{ item.label }}</span>
      </span>
    </template>
  </Breadcrumb>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import Breadcrumb from 'primevue/breadcrumb'

const route = useRoute()

const formatLabel = (segment) => {
  return segment
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

const home = {
  icon: 'pi pi-home',
  route: '/',
}

const breadcrumbs = computed(() => {
  const paths = route.path.split('/').filter(Boolean)

  return paths.map((segment, index) => {
    const path = '/' + paths.slice(0, index + 1).join('/')
    const isLast = index === paths.length - 1

    return {
      label: formatLabel(segment),
      route: isLast ? undefined : path,
    }
  })
})
</script>

<style scoped>
:deep(.p-breadcrumb) {
  padding: 0.75rem 1rem;
  background: transparent;
  border: none;
}
</style>
