// frontend/vue/primevue/minimal/src/components/common/DateRangePicker.vue
<template>
  <div class="date-range-picker">
    <div class="flex flex-wrap align-items-center gap-3">
      <!-- From Date -->
      <div class="flex flex-column gap-1">
        <label v-if="showLabels" class="text-sm font-medium" :for="fromId">{{ fromLabel }}</label>
        <DatePicker
          :id="fromId"
          v-model="fromDate"
          :class="inputClass"
          date-format="yy-mm-dd"
          icon-display="input"
          :max-date="toDate || undefined"
          :placeholder="fromLabel"
          show-button-bar
          show-icon
        />
      </div>

      <!-- To Date -->
      <div class="flex flex-column gap-1">
        <label v-if="showLabels" class="text-sm font-medium" :for="toId">{{ toLabel }}</label>
        <DatePicker
          :id="toId"
          v-model="toDate"
          :class="inputClass"
          date-format="yy-mm-dd"
          icon-display="input"
          :min-date="fromDate || undefined"
          :placeholder="toLabel"
          show-button-bar
          show-icon
        />
      </div>

      <!-- Presets -->
      <div v-if="showPresets" class="flex flex-column gap-1">
        <label v-if="showLabels" class="text-sm font-medium">&nbsp;</label>
        <Select
          v-model="selectedPreset"
          :class="inputClass"
          option-label="label"
          option-value="value"
          :options="presetSelectItems"
          placeholder="Quick Select"
          show-clear
          @update:model-value="handlePresetSelect"
        />
      </div>

      <!-- Clear Button (when not showing presets) -->
      <div v-if="!showPresets && (fromDate || toDate)" class="flex flex-column gap-1">
        <label v-if="showLabels" class="text-sm font-medium">&nbsp;</label>
        <Button
          v-tooltip.top="'Clear dates'"
          icon="pi pi-times"
          rounded
          severity="secondary"
          text
          @click="clearDates"
        />
      </div>
    </div>
  </div>
</template>

<script setup>
  import Button from 'primevue/button'
  import DatePicker from 'primevue/datepicker'
  import Select from 'primevue/select'
  import { computed, ref, watch } from 'vue'

  const props = defineProps({
    /**
     * v-model for the date range object { from: Date | null, to: Date | null }
     */
    modelValue: {
      type: Object,
      default: () => ({ from: null, to: null }),
    },
    /**
     * Label for the from date field
     */
    fromLabel: {
      type: String,
      default: 'From Date',
    },
    /**
     * Label for the to date field
     */
    toLabel: {
      type: String,
      default: 'To Date',
    },
    /**
     * Show labels above the inputs
     */
    showLabels: {
      type: Boolean,
      default: false,
    },
    /**
     * Show preset date range options
     */
    showPresets: {
      type: Boolean,
      default: true,
    },
    /**
     * CSS class for inputs
     */
    inputClass: {
      type: String,
      default: 'w-10rem',
    },
    /**
     * Custom presets (overrides default presets)
     */
    presets: {
      type: Array,
      default: null,
    },
  })

  const emit = defineEmits([
    /**
     * Emitted when the date range changes
     */
    'update:modelValue',
    /**
     * Emitted when the date range changes
     */
    'change',
  ])

  // Unique IDs for accessibility
  const fromId = `from-date-${Math.random().toString(36).slice(2, 9)}`
  const toId = `to-date-${Math.random().toString(36).slice(2, 9)}`

  const fromDate = ref(props.modelValue?.from || null)
  const toDate = ref(props.modelValue?.to || null)
  const selectedPreset = ref(null)

  // Default presets
  const defaultPresets = [
    {
      label: 'Today',
      getValue: () => {
        const today = new Date()
        today.setHours(0, 0, 0, 0)
        return { from: new Date(today), to: new Date(today) }
      },
    },
    {
      label: 'Yesterday',
      getValue: () => {
        const yesterday = new Date()
        yesterday.setDate(yesterday.getDate() - 1)
        yesterday.setHours(0, 0, 0, 0)
        return { from: new Date(yesterday), to: new Date(yesterday) }
      },
    },
    {
      label: 'Last 7 Days',
      getValue: () => {
        const today = new Date()
        today.setHours(0, 0, 0, 0)
        const weekAgo = new Date(today)
        weekAgo.setDate(today.getDate() - 7)
        return { from: weekAgo, to: new Date(today) }
      },
    },
    {
      label: 'Last 30 Days',
      getValue: () => {
        const today = new Date()
        today.setHours(0, 0, 0, 0)
        const monthAgo = new Date(today)
        monthAgo.setDate(today.getDate() - 30)
        return { from: monthAgo, to: new Date(today) }
      },
    },
    {
      label: 'This Month',
      getValue: () => {
        const today = new Date()
        today.setHours(0, 0, 0, 0)
        const firstDay = new Date(today.getFullYear(), today.getMonth(), 1)
        return { from: firstDay, to: new Date(today) }
      },
    },
    {
      label: 'Last Month',
      getValue: () => {
        const today = new Date()
        const firstDayLastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1)
        const lastDayLastMonth = new Date(today.getFullYear(), today.getMonth(), 0)
        return { from: firstDayLastMonth, to: lastDayLastMonth }
      },
    },
  ]

  const presetOptions = computed(() => props.presets || defaultPresets)

  const presetSelectItems = computed(() =>
    presetOptions.value.map(p => ({ label: p.label, value: p.label })),
  )

  // Watch for external model changes
  watch(
    () => props.modelValue,
    newValue => {
      if (newValue?.from !== fromDate.value) {
        fromDate.value = newValue?.from || null
      }
      if (newValue?.to !== toDate.value) {
        toDate.value = newValue?.to || null
      }
    },
    { deep: true },
  )

  // Emit changes when dates change
  watch([fromDate, toDate], ([newFrom, newTo]) => {
    const range = { from: newFrom, to: newTo }
    emit('update:modelValue', range)
    emit('change', range)
    // Clear preset selection when manually changing dates
    selectedPreset.value = null
  })

  function applyPreset (preset) {
    const { from, to } = preset.getValue()
    fromDate.value = from
    toDate.value = to
    selectedPreset.value = preset.label
  }

  function handlePresetSelect (presetLabel) {
    if (!presetLabel) {
      clearDates()
      return
    }
    const preset = presetOptions.value.find(p => p.label === presetLabel)
    if (preset) {
      applyPreset(preset)
    }
  }

  function clearDates () {
    fromDate.value = null
    toDate.value = null
    selectedPreset.value = null
  }

  /**
   * Format date to ISO string (YYYY-MM-DD) for API calls
   */
  function formatDateToString (date) {
    if (!date) return null
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    return `${year}-${month}-${day}`
  }

  /**
   * Get the date range as formatted strings
   */
  function getFormattedRange () {
    return {
      from: formatDateToString(fromDate.value),
      to: formatDateToString(toDate.value),
    }
  }

  // Expose methods for parent component
  defineExpose({
    clearDates,
    applyPreset,
    getFormattedRange,
  })
</script>

<style scoped>
.date-range-picker {
  width: 100%;
}
</style>

// frontend/react/primereact/full/src/components/common/DateRangePicker.tsx
import { useMemo, useRef } from 'react'
import { Calendar } from 'primereact/calendar'
import { Button } from 'primereact/button'
import { Menu } from 'primereact/menu'
import { MenuItem } from 'primereact/menuitem'
import { Nullable } from 'primereact/ts-helpers'

export interface DateRange {
  from: Date | null
  to: Date | null
}

interface DateRangePickerProps {
  /** Current date range value */
  value: DateRange
  /** Callback when date range changes */
  onChange: (value: DateRange) => void
  /** Label for the from date field */
  fromLabel?: string
  /** Label for the to date field */
  toLabel?: string
  /** Disable the date pickers */
  disabled?: boolean
  /** Show presets dropdown */
  showPresets?: boolean
  /** Show clear button */
  showClear?: boolean
  /** Date format for display */
  dateFormat?: string
}

interface DatePreset {
  label: string
  getValue: () => DateRange
}

const getPresets = (): DatePreset[] => {
  const today = new Date()
  today.setHours(0, 0, 0, 0)

  return [
    {
      label: 'Today',
      getValue: () => ({
        from: new Date(today),
        to: new Date(today),
      }),
    },
    {
      label: 'Last 7 days',
      getValue: () => {
        const from = new Date(today)
        from.setDate(from.getDate() - 6)
        return {
          from,
          to: new Date(today),
        }
      },
    },
    {
      label: 'Last 30 days',
      getValue: () => {
        const from = new Date(today)
        from.setDate(from.getDate() - 29)
        return {
          from,
          to: new Date(today),
        }
      },
    },
    {
      label: 'This month',
      getValue: () => {
        const from = new Date(today.getFullYear(), today.getMonth(), 1)
        const to = new Date(today.getFullYear(), today.getMonth() + 1, 0)
        return {
          from,
          to,
        }
      },
    },
  ]
}

export function DateRangePicker({
  value,
  onChange,
  fromLabel = 'From',
  toLabel = 'To',
  disabled = false,
  showPresets = true,
  showClear = true,
  dateFormat = 'yy-mm-dd',
}: DateRangePickerProps) {
  const menuRef = useRef<Menu>(null)
  const presets = useMemo(() => getPresets(), [])

  const handlePresetSelect = (preset: DatePreset) => {
    onChange(preset.getValue())
  }

  const handleFromChange = (date: Nullable<Date>) => {
    onChange({
      ...value,
      from: date || null,
    })
  }

  const handleToChange = (date: Nullable<Date>) => {
    onChange({
      ...value,
      to: date || null,
    })
  }

  const handleClear = () => {
    onChange({ from: null, to: null })
  }

  const hasValue = value.from || value.to

  const menuItems: MenuItem[] = [
    {
      label: 'Date Presets',
      items: presets.map((preset) => ({
        label: preset.label,
        command: () => handlePresetSelect(preset),
      })),
    },
  ]

  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
        flexWrap: 'wrap',
      }}
    >
      <span className="p-float-label">
        <Calendar
          id="from-date"
          value={value.from}
          onChange={(e) => handleFromChange(e.value as Nullable<Date>)}
          dateFormat={dateFormat}
          disabled={disabled}
          maxDate={value.to || undefined}
          showIcon
          showButtonBar
          style={{ width: '170px' }}
        />
        <label htmlFor="from-date">{fromLabel}</label>
      </span>

      <span style={{ color: 'var(--text-color-secondary)' }}>-</span>

      <span className="p-float-label">
        <Calendar
          id="to-date"
          value={value.to}
          onChange={(e) => handleToChange(e.value as Nullable<Date>)}
          dateFormat={dateFormat}
          disabled={disabled}
          minDate={value.from || undefined}
          showIcon
          showButtonBar
          style={{ width: '170px' }}
        />
        <label htmlFor="to-date">{toLabel}</label>
      </span>

      {showPresets && (
        <>
          <Button
            label="Presets"
            icon="pi pi-calendar"
            severity="secondary"
            outlined
            size="small"
            onClick={(e) => menuRef.current?.toggle(e)}
            disabled={disabled}
          />
          <Menu ref={menuRef} model={menuItems} popup />
        </>
      )}

      {showClear && hasValue && (
        <Button
          icon="pi pi-times"
          severity="secondary"
          text
          rounded
          size="small"
          onClick={handleClear}
          disabled={disabled}
          aria-label="Clear dates"
          tooltip="Clear dates"
          tooltipOptions={{ position: 'top' }}
        />
      )}
    </div>
  )
}
