// frontend-primereact/src/pages/ForgotPassword.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { InputText } from 'primereact/inputtext'
import { Button } from 'primereact/button'
import { Card } from 'primereact/card'
import { Message } from 'primereact/message'
import { authApi } from '@/services/authApi'

export default function ForgotPassword() {
  const [email, setEmail] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    try {
      await authApi.forgotPassword(email)
      setSuccess(true)
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to send reset email')
    } finally {
      setLoading(false)
    }
  }

  if (success) {
    return (
      <div className="flex align-items-center justify-content-center min-h-screen surface-ground">
        <Card className="w-full max-w-30rem p-4">
          <div className="text-center">
            <div
              className="flex align-items-center justify-content-center border-round mx-auto mb-4"
              style={{ width: '4rem', height: '4rem', backgroundColor: 'var(--green-100)' }}
            >
              <i className="pi pi-check text-green-500 text-4xl" />
            </div>
            <div className="text-900 text-2xl font-medium mb-3">Check Your Email</div>
            <p className="text-600 mb-4">
              We've sent a password reset link to <strong>{email}</strong>. Please check your inbox
              and follow the instructions to reset your password.
            </p>
            <Link to="/login" className="no-underline">
              <Button label="Back to Login" icon="pi pi-arrow-left" className="w-full" />
            </Link>
          </div>
        </Card>
      </div>
    )
  }

  return (
    <div className="flex align-items-center justify-content-center min-h-screen surface-ground">
      <Card className="w-full max-w-30rem p-4">
        <div className="text-center mb-5">
          <div className="text-900 text-3xl font-medium mb-3">Forgot Password</div>
          <span className="text-600 font-medium">
            Enter your email address and we'll send you a link to reset your password.
          </span>
        </div>

        {error && <Message severity="error" text={error} className="w-full mb-4" />}

        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label htmlFor="email" className="block text-900 font-medium mb-2">
              Email Address
            </label>
            <InputText
              id="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="Enter your email"
              className="w-full"
              required
            />
          </div>

          <Button
            type="submit"
            label="Send Reset Link"
            icon="pi pi-send"
            className="w-full mb-3"
            loading={loading}
          />

          <div className="text-center">
            <Link to="/login" className="text-primary no-underline">
              Back to Login
            </Link>
          </div>
        </form>
      </Card>
    </div>
  )
}

// frontend-primevue/src/pages/forgot-password.vue
<template>
  <div class="forgot-password-container">
    <div class="forgot-password-card">
      <div class="card-header">
        <i class="pi pi-lock logo-icon"></i>
        <h1 class="card-title">Forgot Password</h1>
        <p class="card-subtitle">
          Enter your email address and we'll send you a link to reset your password.
        </p>
      </div>

      <form v-if="!submitted" @submit.prevent="handleSubmit" class="forgot-password-form">
        <Message v-if="error" severity="error" :closable="false">
          {{ error }}
        </Message>

        <div class="form-field">
          <label for="email">Email Address</label>
          <InputText
            id="email"
            v-model="email"
            type="email"
            placeholder="Enter your email"
            :disabled="loading"
            :invalid="!!emailError"
            class="w-full"
          />
          <small v-if="emailError" class="p-error">{{ emailError }}</small>
        </div>

        <Button
          type="submit"
          label="Send Reset Link"
          :loading="loading"
          class="w-full"
          size="large"
        />

        <div class="back-to-login">
          <router-link to="/login" class="back-link">
            <i class="pi pi-arrow-left"></i>
            Back to Login
          </router-link>
        </div>
      </form>

      <div v-else class="success-state">
        <div class="success-icon">
          <i class="pi pi-check-circle"></i>
        </div>
        <h2>Check Your Email</h2>
        <p>
          If an account exists for <strong>{{ email }}</strong>, you will receive a password
          reset link shortly.
        </p>
        <Button
          label="Back to Login"
          severity="secondary"
          @click="$router.push('/login')"
          class="w-full"
        />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import authApi from '@/services/authApi'
import InputText from 'primevue/inputtext'
import Button from 'primevue/button'
import Message from 'primevue/message'

definePage({
  meta: {
    layout: 'blank',
  },
})

const email = ref('')
const emailError = ref('')
const error = ref('')
const loading = ref(false)
const submitted = ref(false)

const validate = () => {
  emailError.value = ''

  if (!email.value.trim()) {
    emailError.value = 'Email is required'
    return false
  }

  if (!/\S+@\S+\.\S+/.test(email.value)) {
    emailError.value = 'Invalid email format'
    return false
  }

  return true
}

const handleSubmit = async () => {
  if (!validate()) return

  loading.value = true
  error.value = ''

  try {
    await authApi.forgotPassword(email.value)
    submitted.value = true
  } catch (err) {
    // Don't reveal if email exists or not
    submitted.value = true
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.forgot-password-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.forgot-password-card {
  width: 100%;
  max-width: 420px;
  background: white;
  border-radius: 1rem;
  padding: 2.5rem;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
}

.card-header {
  text-align: center;
  margin-bottom: 2rem;
}

.logo-icon {
  font-size: 3rem;
  color: #667eea;
  margin-bottom: 1rem;
}

.card-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: #1f2937;
  margin: 0 0 0.75rem 0;
}

.card-subtitle {
  font-size: 0.875rem;
  color: #6b7280;
  margin: 0;
  line-height: 1.5;
}

.forgot-password-form {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-field label {
  font-weight: 500;
  font-size: 0.875rem;
  color: #374151;
}

.back-to-login {
  text-align: center;
}

.back-link {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  color: #667eea;
  text-decoration: none;
  font-size: 0.875rem;
}

.back-link:hover {
  text-decoration: underline;
}

.success-state {
  text-align: center;
}

.success-icon {
  margin-bottom: 1rem;
}

.success-icon i {
  font-size: 4rem;
  color: #10b981;
}

.success-state h2 {
  font-size: 1.25rem;
  font-weight: 600;
  color: #1f2937;
  margin: 0 0 0.75rem 0;
}

.success-state p {
  font-size: 0.875rem;
  color: #6b7280;
  margin: 0 0 1.5rem 0;
  line-height: 1.5;
}

.w-full {
  width: 100%;
}
</style>
