// frontend-primevue/src/pages/departments/index.vue
<template>
  <div class="departments-page">


    <!-- Departments Table -->
    <Card>
      <template #content>
        <DataTable
          :value="departments"
          :loading="loading"
          paginator
          :rows="10"
          :rowsPerPageOptions="[5, 10, 25, 50]"
          dataKey="id"
          filterDisplay="row"
          v-model:filters="filters"
          :globalFilterFields="['code', 'name']"
          responsiveLayout="scroll"
          class="departments-table"
        >
          <template #header>
            <div class="flex flex-wrap align-items-center justify-content-between gap-2">
              <IconField>
                <InputIcon class="pi pi-search" />
                <InputText
                  v-model="filters['global'].value"
                  placeholder="Search departments..."
                  class="w-20rem"
                />
              </IconField>
              <Button label="Add Department" icon="pi pi-building" @click="openCreateDialog" />
            </div>
          </template>

          <template #empty>
            <div class="table-empty">
              <i class="pi pi-building"></i>
              <span>No departments found</span>
            </div>
          </template>

          <Column field="code" header="Code" sortable style="min-width: 120px">
            <template #body="{ data }">
              <Tag :value="data.code" severity="secondary" />
            </template>
          </Column>

          <Column field="name" header="Name" sortable style="min-width: 200px" />

          <Column field="description" header="Description" style="min-width: 300px">
            <template #body="{ data }">
              {{ data.description || '-' }}
            </template>
          </Column>

          <Column field="isActive" header="Status" sortable style="min-width: 100px">
            <template #body="{ data }">
              <Tag
                :value="data.isActive ? 'Active' : 'Inactive'"
                :severity="data.isActive ? 'success' : 'secondary'"
              />
            </template>
          </Column>

          <Column field="createdAt" header="Created" sortable style="min-width: 150px">
            <template #body="{ data }">
              {{ formatDate(data.createdAt) }}
            </template>
          </Column>

          <Column header="Actions" style="min-width: 120px">
            <template #body="{ data }">
              <div class="action-buttons">
                <Button
                  icon="pi pi-pencil"
                  text
                  rounded
                  severity="info"
                  @click="openEditDialog(data)"
                  v-tooltip.top="'Edit'"
                />
                <Button
                  icon="pi pi-trash"
                  text
                  rounded
                  severity="danger"
                  @click="handleDelete(data)"
                  v-tooltip.top="'Delete'"
                />
              </div>
            </template>
          </Column>
        </DataTable>
      </template>
    </Card>

    <!-- Create/Edit Dialog -->
    <Dialog
      v-model:visible="dialogVisible"
      :header="editingDepartment ? 'Edit Department' : 'Create New Department'"
      :style="{ width: '32rem' }"
      modal
    >
      <div class="flex flex-column gap-3">
        <div class="flex flex-column gap-2 mb-4">
          <label for="code">Code *</label>
          <InputText
            id="code"
            v-model="form.code"
            :disabled="!!editingDepartment"
            :invalid="!!formErrors.code"
            class="w-full"
            placeholder="e.g., IT, HR, FIN"
          />
          <small v-if="formErrors.code" class="text-red-500">{{ formErrors.code }}</small>
        </div>

        <div class="flex flex-column gap-2 mb-4">
          <label for="name">Name *</label>
          <InputText
            id="name"
            v-model="form.name"
            :invalid="!!formErrors.name"
            class="w-full"
            placeholder="e.g., Information Technology"
          />
          <small v-if="formErrors.name" class="text-red-500">{{ formErrors.name }}</small>
        </div>

        <div class="flex flex-column gap-2 mb-4">
          <label for="description">Description</label>
          <Textarea
            id="description"
            v-model="form.description"
            rows="3"
            class="w-full"
            placeholder="Optional description..."
          />
        </div>

        <div v-if="editingDepartment" class="flex align-items-center gap-2">
          <ToggleSwitch id="isActive" v-model="form.isActive" />
          <label for="isActive">Status: {{ form.isActive ? 'Active' : 'Inactive' }}</label>
        </div>


      </div>
      <template #footer>
        <Button label="Cancel" severity="secondary" @click="closeDialog" />
        <Button
          :label="editingDepartment ? 'Update' : 'Create'"
          :loading="saving"
          @click="handleSubmit"
        />
      </template>
    </Dialog>
  </div>
</template>

<script setup>
import { ref, reactive, computed, onMounted } from 'vue'
import { useDepartmentStore } from '@/stores/department'
import { useNotificationStore } from '@/stores/notification'
import { useConfirmDialog } from '@/composables/useConfirmDialog'
import { FilterMatchMode } from '@primevue/core/api'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Card from 'primevue/card'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import Textarea from 'primevue/textarea'
import Dialog from 'primevue/dialog'
import Tag from 'primevue/tag'
import ToggleSwitch from 'primevue/toggleswitch'
import IconField from 'primevue/iconfield'
import InputIcon from 'primevue/inputicon'

const departmentStore = useDepartmentStore()
const notificationStore = useNotificationStore()
const { confirmDelete } = useConfirmDialog()

const loading = ref(false)
const saving = ref(false)
const dialogVisible = ref(false)
const editingDepartment = ref(null)

const filters = ref({
  global: { value: null, matchMode: FilterMatchMode.CONTAINS },
})

const departments = computed(() => departmentStore.departments)

const form = reactive({
  code: '',
  name: '',
  description: '',
  isActive: true,
})

const formErrors = reactive({
  code: '',
  name: '',
})

const formatDate = (dateString) => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

const resetForm = () => {
  form.code = ''
  form.name = ''
  form.description = ''
  form.isActive = true
  Object.keys(formErrors).forEach((key) => (formErrors[key] = ''))
}

const openCreateDialog = () => {
  editingDepartment.value = null
  resetForm()
  dialogVisible.value = true
}

const openEditDialog = (department) => {
  editingDepartment.value = department
  form.code = department.code
  form.name = department.name
  form.description = department.description || ''
  form.isActive = department.isActive
  Object.keys(formErrors).forEach((key) => (formErrors[key] = ''))
  dialogVisible.value = true
}

const closeDialog = () => {
  dialogVisible.value = false
  editingDepartment.value = null
}

const validate = () => {
  let valid = true
  Object.keys(formErrors).forEach((key) => (formErrors[key] = ''))

  if (!form.code.trim()) {
    formErrors.code = 'Code is required'
    valid = false
  }

  if (!form.name.trim()) {
    formErrors.name = 'Name is required'
    valid = false
  }

  return valid
}

const handleSubmit = async () => {
  if (!validate()) return

  saving.value = true
  try {
    if (editingDepartment.value) {
      await departmentStore.updateDepartment(editingDepartment.value.id, {
        name: form.name,
        description: form.description,
        isActive: form.isActive,
      })
      notificationStore.success('Department updated successfully')
    } else {
      await departmentStore.createDepartment({
        code: form.code,
        name: form.name,
        description: form.description,
      })
      notificationStore.success('Department created successfully')
    }
    await departmentStore.fetchDepartments()
    closeDialog()
  } catch (error) {
    notificationStore.error(error.response?.data?.message || 'Operation failed')
  } finally {
    saving.value = false
  }
}

const handleDelete = async (department) => {
  const confirmed = await confirmDelete(department.name)
  if (!confirmed) return

  try {
    await departmentStore.deleteDepartment(department.id)
    notificationStore.success('Department deleted successfully')
    await departmentStore.fetchDepartments()
  } catch (error) {
    notificationStore.error(error.response?.data?.message || 'Delete failed')
  }
}

onMounted(async () => {
  loading.value = true
  try {
    await departmentStore.fetchDepartments()
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
.departments-page {
  padding: 1rem;
}



.table-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 3rem;
  gap: 0.5rem;
  color: var(--p-text-muted-color);
}

.table-empty i {
  font-size: 3rem;
}

.action-buttons {
  display: flex;
  gap: 0.25rem;
}

.text-red-500 {
  color: var(--p-red-500);
}
</style>

// frontend/react/primereact/full/src/pages/Departments.tsx
import { useState, useEffect } from 'react'
import { DataTable, DataTableFilterMeta } from 'primereact/datatable'
import { Column } from 'primereact/column'
import { Button } from 'primereact/button'
import { Dialog } from 'primereact/dialog'
import { InputText } from 'primereact/inputtext'
import { InputTextarea } from 'primereact/inputtextarea'
import { InputSwitch } from 'primereact/inputswitch'
import { Tag } from 'primereact/tag'
import { Card } from 'primereact/card'
import { IconField } from 'primereact/iconfield'
import { InputIcon } from 'primereact/inputicon'
import { FilterMatchMode } from 'primereact/api'
import { ConfirmDialog } from '@/components'
import { useDepartmentStore } from '@/stores/departmentStore'
import { useNotificationStore } from '@/stores/notificationStore'
import type { Department, CreateDepartmentRequest, UpdateDepartmentRequest } from '@/types/department'

interface FormData {
  name: string
  code: string
  description: string
  isActive: boolean
}

interface FormErrors {
  code: string
  name: string
}

export default function Departments() {
  const { departments, loading, fetchDepartments, createDepartment, updateDepartment, deleteDepartment } =
    useDepartmentStore()
  const showSuccess = useNotificationStore((state) => state.showSuccess)

  const [dialogVisible, setDialogVisible] = useState(false)
  const [deleteDialogVisible, setDeleteDialogVisible] = useState(false)
  const [selectedDepartment, setSelectedDepartment] = useState<Department | null>(null)
  const [isEditing, setIsEditing] = useState(false)
  const [saving, setSaving] = useState(false)

  const [filters, setFilters] = useState<DataTableFilterMeta>({
    global: { value: null, matchMode: FilterMatchMode.CONTAINS },
  })
  const [globalFilterValue, setGlobalFilterValue] = useState('')

  const [formData, setFormData] = useState<FormData>({
    name: '',
    code: '',
    description: '',
    isActive: true,
  })

  const [formErrors, setFormErrors] = useState<FormErrors>({
    code: '',
    name: '',
  })

  useEffect(() => {
    fetchDepartments()
  }, [fetchDepartments])

  const onGlobalFilterChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value
    const _filters = { ...filters }
    ;(_filters['global'] as any).value = value
    setFilters(_filters)
    setGlobalFilterValue(value)
  }

  const formatDate = (dateString: string | undefined): string => {
    if (!dateString) return '-'
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })
  }

  const resetForm = () => {
    setFormData({
      name: '',
      code: '',
      description: '',
      isActive: true,
    })
    setFormErrors({ code: '', name: '' })
  }

  const openCreateDialog = () => {
    resetForm()
    setIsEditing(false)
    setDialogVisible(true)
  }

  const openEditDialog = (department: Department) => {
    setFormData({
      name: department.name,
      code: department.code,
      description: department.description || '',
      isActive: department.isActive,
    })
    setFormErrors({ code: '', name: '' })
    setSelectedDepartment(department)
    setIsEditing(true)
    setDialogVisible(true)
  }

  const openDeleteDialog = (department: Department) => {
    setSelectedDepartment(department)
    setDeleteDialogVisible(true)
  }

  const validate = (): boolean => {
    const errors: FormErrors = { code: '', name: '' }
    let valid = true

    if (!formData.code.trim()) {
      errors.code = 'Code is required'
      valid = false
    }

    if (!formData.name.trim()) {
      errors.name = 'Name is required'
      valid = false
    }

    setFormErrors(errors)
    return valid
  }

  const handleSubmit = async () => {
    if (!validate()) return

    setSaving(true)
    try {
      if (isEditing && selectedDepartment) {
        const updateData: UpdateDepartmentRequest = {
          name: formData.name,
          description: formData.description,
          isActive: formData.isActive,
        }
        await updateDepartment(selectedDepartment.id, updateData)
        showSuccess('Department updated successfully')
      } else {
        const createData: CreateDepartmentRequest = {
          code: formData.code,
          name: formData.name,
          description: formData.description,
        }
        await createDepartment(createData)
        showSuccess('Department created successfully')
      }
      setDialogVisible(false)
      await fetchDepartments()
    } catch {
      // Error toast is shown automatically by API interceptor
    } finally {
      setSaving(false)
    }
  }

  const handleDelete = async () => {
    if (selectedDepartment) {
      try {
        await deleteDepartment(selectedDepartment.id)
        showSuccess('Department deleted successfully')
        setDeleteDialogVisible(false)
        await fetchDepartments()
      } catch {
        // Error toast is shown automatically by API interceptor
      }
    }
  }

  const codeTemplate = (department: Department) => (
    <Tag value={department.code} severity="secondary" />
  )

  const statusTemplate = (department: Department) => (
    <Tag
      value={department.isActive ? 'Active' : 'Inactive'}
      severity={department.isActive ? 'success' : 'secondary'}
    />
  )

  const actionsTemplate = (department: Department) => (
    <div className="flex gap-1">
      <Button
        icon="pi pi-pencil"
        rounded
        text
        severity="info"
        onClick={() => openEditDialog(department)}
        tooltip="Edit"
        tooltipOptions={{ position: 'top' }}
      />
      <Button
        icon="pi pi-trash"
        rounded
        text
        severity="danger"
        onClick={() => openDeleteDialog(department)}
        tooltip="Delete"
        tooltipOptions={{ position: 'top' }}
      />
    </div>
  )

  const renderHeader = () => (
    <div className="flex flex-wrap align-items-center justify-content-between gap-2">
      <IconField iconPosition="left">
        <InputIcon className="pi pi-search" />
        <InputText
          value={globalFilterValue}
          onChange={onGlobalFilterChange}
          placeholder="Search departments..."
          style={{ width: '20rem' }}
        />
      </IconField>
      <Button label="Add Department" icon="pi pi-building" onClick={openCreateDialog} />
    </div>
  )

  const emptyMessage = (
    <div className="flex flex-column align-items-center p-5 text-color-secondary">
      <i className="pi pi-building text-5xl mb-3"></i>
      <span>No departments found</span>
    </div>
  )

  const dialogFooter = (
    <div className="flex justify-content-end gap-2">
      <Button label="Cancel" severity="secondary" onClick={() => setDialogVisible(false)} />
      <Button label={isEditing ? 'Update' : 'Create'} onClick={handleSubmit} loading={saving} />
    </div>
  )

  return (
    <div className="p-3">
      <Card>
        <DataTable
          value={departments}
          loading={loading}
          paginator
          rows={10}
          rowsPerPageOptions={[5, 10, 25, 50]}
          dataKey="id"
          filters={filters}
          filterDisplay="row"
          globalFilterFields={['code', 'name']}
          header={renderHeader()}
          emptyMessage={emptyMessage}
          stripedRows
        >
          <Column
            field="code"
            header="Code"
            body={codeTemplate}
            sortable
            style={{ minWidth: '120px' }}
          />
          <Column field="name" header="Name" sortable style={{ minWidth: '200px' }} />
          <Column
            field="description"
            header="Description"
            style={{ minWidth: '300px' }}
            body={(data) => data.description || '-'}
          />
          <Column
            field="isActive"
            header="Status"
            body={statusTemplate}
            sortable
            style={{ minWidth: '100px' }}
          />
          <Column
            field="createdAt"
            header="Created"
            sortable
            style={{ minWidth: '150px' }}
            body={(data) => formatDate(data.createdAt)}
          />
          <Column header="Actions" body={actionsTemplate} style={{ minWidth: '120px' }} />
        </DataTable>
      </Card>

      <Dialog
        header={isEditing ? 'Edit Department' : 'Create New Department'}
        visible={dialogVisible}
        onHide={() => setDialogVisible(false)}
        footer={dialogFooter}
        style={{ width: '32rem' }}
        modal
      >
        <div className="flex flex-column gap-3">
          <div className="flex flex-column gap-2 mb-2">
            <label htmlFor="code">Code *</label>
            <InputText
              id="code"
              value={formData.code}
              onChange={(e) => setFormData({ ...formData, code: e.target.value })}
              disabled={isEditing}
              invalid={!!formErrors.code}
              placeholder="e.g., IT, HR, FIN"
              className="w-full"
            />
            {formErrors.code && <small className="text-red-500">{formErrors.code}</small>}
          </div>

          <div className="flex flex-column gap-2 mb-2">
            <label htmlFor="name">Name *</label>
            <InputText
              id="name"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              invalid={!!formErrors.name}
              placeholder="e.g., Information Technology"
              className="w-full"
            />
            {formErrors.name && <small className="text-red-500">{formErrors.name}</small>}
          </div>

          <div className="flex flex-column gap-2 mb-2">
            <label htmlFor="description">Description</label>
            <InputTextarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              rows={3}
              placeholder="Optional description..."
              className="w-full"
            />
          </div>

          {isEditing && (
            <div className="flex align-items-center gap-3">
              <InputSwitch
                checked={formData.isActive}
                onChange={(e) => setFormData({ ...formData, isActive: e.value ?? false })}
              />
              <label>Status: {formData.isActive ? 'Active' : 'Inactive'}</label>
            </div>
          )}
        </div>
      </Dialog>

      <ConfirmDialog
        visible={deleteDialogVisible}
        title="Delete Department"
        message={`Are you sure you want to delete department "${selectedDepartment?.name}"?`}
        confirmLabel="Delete"
        confirmSeverity="danger"
        onConfirm={handleDelete}
        onCancel={() => setDeleteDialogVisible(false)}
      />
    </div>
  )
}
