// frontend/vue/primevue/minimal/src/pages/forgot-password.vue
<template>
  <div class="forgot-password-container">
    <div class="forgot-password-card">
      <div class="card-header">
        <i class="pi pi-lock logo-icon" />
        <h1 class="card-title">Forgot Password</h1>
        <p class="card-subtitle">
          Enter your email address and we'll send you a link to reset your password.
        </p>
      </div>

      <form v-if="!submitted" class="forgot-password-form" @submit.prevent="handleSubmit">
        <Message v-if="error" :closable="false" severity="error">
          {{ error }}
        </Message>

        <div class="form-field">
          <label for="email">Email Address</label>
          <InputText
            id="email"
            v-model="email"
            class="w-full"
            :disabled="loading"
            :invalid="!!emailError"
            placeholder="Enter your email"
            type="email"
          />
          <small v-if="emailError" class="p-error">{{ emailError }}</small>
        </div>

        <Button
          class="w-full"
          label="Send Reset Link"
          :loading="loading"
          size="large"
          type="submit"
        />

        <div class="back-to-login">
          <router-link class="back-link" to="/login">
            <i class="pi pi-arrow-left" />
            Back to Login
          </router-link>
        </div>
      </form>

      <div v-else class="success-state">
        <div class="success-icon">
          <i class="pi pi-check-circle" />
        </div>
        <h2>Check Your Email</h2>
        <p>
          If an account exists for <strong>{{ email }}</strong>, you will receive a password
          reset link shortly.
        </p>
        <Button
          class="w-full"
          label="Back to Login"
          severity="secondary"
          @click="$router.push('/login')"
        />
      </div>
    </div>
  </div>
</template>

<script setup>
  import Button from 'primevue/button'
  import InputText from 'primevue/inputtext'
  import Message from 'primevue/message'
  import { ref } from 'vue'
  import authApi from '@/services/authApi'

  definePage({
    meta: {
      layout: 'blank',
    },
  })

  const email = ref('')
  const emailError = ref('')
  const error = ref('')
  const loading = ref(false)
  const submitted = ref(false)

  function validate () {
    emailError.value = ''

    if (!email.value.trim()) {
      emailError.value = 'Email is required'
      return false
    }

    if (!/\S+@\S+\.\S+/.test(email.value)) {
      emailError.value = 'Invalid email format'
      return false
    }

    return true
  }

  async function handleSubmit () {
    if (!validate()) return

    loading.value = true
    error.value = ''

    try {
      await authApi.forgotPassword(email.value)
      submitted.value = true
    } catch {
      // Don't reveal if email exists or not
      submitted.value = true
    } finally {
      loading.value = false
    }
  }
</script>

<style scoped>
.forgot-password-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  background: linear-gradient(135deg, #1e3a5f 0%, #0d1b2a 50%, #1b263b 100%);
}

.forgot-password-card {
  width: 100%;
  max-width: 420px;
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(20px);
  border-radius: 24px;
  padding: 2.5rem;
  box-shadow:
    0 25px 50px -12px rgba(0, 0, 0, 0.4),
    0 0 0 1px rgba(255, 255, 255, 0.1),
    inset 0 1px 0 rgba(255, 255, 255, 0.5);
}

.card-header {
  text-align: center;
  margin-bottom: 2rem;
}

.logo-icon {
  font-size: 3rem;
  color: #6366f1;
  margin-bottom: 1rem;
}

.card-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: #0f172a;
  margin: 0 0 0.75rem 0;
}

.card-subtitle {
  font-size: 0.875rem;
  color: #64748b;
  margin: 0;
  line-height: 1.5;
}

.forgot-password-form {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
}

.form-field {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-field label {
  font-weight: 600;
  font-size: 0.875rem;
  color: #334155;
}

.back-to-login {
  text-align: center;
}

.back-link {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  color: #6366f1;
  text-decoration: none;
  font-size: 0.875rem;
}

.back-link:hover {
  text-decoration: underline;
}

.success-state {
  text-align: center;
}

.success-icon {
  margin-bottom: 1rem;
}

.success-icon i {
  font-size: 4rem;
  color: #10b981;
}

.success-state h2 {
  font-size: 1.25rem;
  font-weight: 600;
  color: #0f172a;
  margin: 0 0 0.75rem 0;
}

.success-state p {
  font-size: 0.875rem;
  color: #64748b;
  margin: 0 0 1.5rem 0;
  line-height: 1.5;
}

.w-full {
  width: 100%;
}
</style>

// frontend/react/primereact/full/src/pages/ForgotPassword.tsx
import React, { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { InputText } from 'primereact/inputtext'
import { Button } from 'primereact/button'
import { Message } from 'primereact/message'
import { authApi } from '@/services/authApi'
import '@/styles/auth.scss'

export default function ForgotPassword() {
  const navigate = useNavigate()
  const [email, setEmail] = useState('')
  const [emailError, setEmailError] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [submitted, setSubmitted] = useState(false)

  const validate = (): boolean => {
    setEmailError('')

    if (!email.trim()) {
      setEmailError('Email is required')
      return false
    }

    if (!/\S+@\S+\.\S+/.test(email)) {
      setEmailError('Invalid email format')
      return false
    }

    return true
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!validate()) return

    setLoading(true)
    setError('')

    try {
      await authApi.forgotPassword(email)
      setSubmitted(true)
    } catch {
      // Don't reveal if email exists or not
      setSubmitted(true)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="auth-page forgot-password">
      <div className="auth-card">
        <div className="card-content">
          {/* Header */}
          <div className="auth-header">
            <div className="logo-wrapper purple">
              <i className="pi pi-lock"></i>
            </div>
            <h1>Forgot Password</h1>
            <p>Enter your email address and we'll send you a link to reset your password.</p>
          </div>

          {!submitted ? (
            <form onSubmit={handleSubmit} className="auth-form">
              {error && (
                <Message severity="error" text={error} className="mb-4 w-full" />
              )}

              <div className="field">
                <label htmlFor="email">Email Address</label>
                <InputText
                  id="email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  disabled={loading}
                  invalid={!!emailError}
                  size="large"
                />
                {emailError && <small className="p-error">{emailError}</small>}
              </div>

              <Button
                type="submit"
                label="Send Reset Link"
                loading={loading}
                size="large"
                className="submit-button purple"
              />

              <div className="back-to-login">
                <Link to="/login" className="back-link purple">
                  <i className="pi pi-arrow-left"></i>
                  Back to Login
                </Link>
              </div>
            </form>
          ) : (
            <div className="success-state">
              <div className="success-icon">
                <i className="pi pi-check-circle"></i>
              </div>
              <h2>Check Your Email</h2>
              <p>
                If an account exists for <strong>{email}</strong>, you will receive a password
                reset link shortly.
              </p>
              <Button
                label="Back to Login"
                severity="secondary"
                size="large"
                onClick={() => navigate('/login')}
                className="w-full"
              />
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
