// frontend/vue/vuetify/minimal/src/components/common/ExportButton.vue
<template>
  <v-menu v-model="menu" :close-on-content-click="false" location="bottom end">
    <template #activator="{ props }">
      <v-btn
        v-bind="props"
        color="primary"
        :disabled="disabled"
        :loading="loading"
        prepend-icon="mdi-download"
        variant="outlined"
      >
        Export
        <v-icon end>mdi-chevron-down</v-icon>
      </v-btn>
    </template>

    <v-card min-width="200">
      <v-list density="compact">
        <v-list-subheader>Export Format</v-list-subheader>

        <v-list-item
          v-for="format in formats"
          :key="format.value"
          :prepend-icon="format.icon"
          :title="format.label"
          @click="handleExport(format.value)"
        />
      </v-list>
    </v-card>
  </v-menu>
</template>

<script setup>
  import { ref } from 'vue'
  import { useNotificationStore } from '@/stores/notification'

  const props = defineProps({
    exportFn: {
      type: Function,
      required: true,
    },
    filters: {
      type: Object,
      default: () => ({}),
    },
    disabled: {
      type: Boolean,
      default: false,
    },
  })

  const emit = defineEmits(['export-start', 'export-complete', 'export-error'])

  const notificationStore = useNotificationStore()
  const menu = ref(false)
  const loading = ref(false)

  const formats = [
    { value: 'xlsx', label: 'Excel (.xlsx)', icon: 'mdi-file-excel' },
    { value: 'csv', label: 'CSV (.csv)', icon: 'mdi-file-delimited' },
    { value: 'pdf', label: 'PDF Report (.pdf)', icon: 'mdi-file-pdf-box' },
  ]

  async function handleExport (format) {
    menu.value = false
    loading.value = true
    emit('export-start', format)

    try {
      const result = await props.exportFn(format, props.filters)
      notificationStore.showSuccess(`Exported successfully: ${result.fileName}`)
      emit('export-complete', result)
    } catch (error) {
      console.error('Export failed:', error)
      notificationStore.showError('Export failed. Please try again.')
      emit('export-error', error)
    } finally {
      loading.value = false
    }
  }
</script>

// frontend/react/primereact/minimal/src/components/common/ExportButton.tsx
import { useState, useRef } from 'react'
import { Button } from 'primereact/button'
import { Menu } from 'primereact/menu'
import { MenuItem } from 'primereact/menuitem'
import { useNotificationStore } from '@/stores'

interface ExportButtonProps {
  exportFn: (format: string, filters: Record<string, any>) => Promise<{ success: boolean; fileName: string }>
  filters?: Record<string, any>
  disabled?: boolean
  onExportStart?: (format: string) => void
  onExportComplete?: (result: { success: boolean; fileName: string }) => void
  onExportError?: (error: Error) => void
}

export function ExportButton({
  exportFn,
  filters = {},
  disabled = false,
  onExportStart,
  onExportComplete,
  onExportError,
}: ExportButtonProps) {
  const [loading, setLoading] = useState(false)
  const menuRef = useRef<Menu>(null)
  const showSuccess = useNotificationStore((state) => state.showSuccess)
  const showError = useNotificationStore((state) => state.showError)

  const handleExport = async (format: string) => {
    setLoading(true)
    onExportStart?.(format)

    try {
      const result = await exportFn(format, filters)
      showSuccess(`Exported successfully: ${result.fileName}`)
      onExportComplete?.(result)
    } catch (error) {
      console.error('Export failed:', error)
      showError('Export failed. Please try again.')
      onExportError?.(error as Error)
    } finally {
      setLoading(false)
    }
  }

  const menuItems: MenuItem[] = [
    {
      label: 'Export Format',
      items: [
        {
          label: 'Excel (.xlsx)',
          icon: 'pi pi-file-excel',
          command: () => handleExport('xlsx'),
        },
        {
          label: 'CSV (.csv)',
          icon: 'pi pi-file',
          command: () => handleExport('csv'),
        },
        {
          label: 'PDF Report (.pdf)',
          icon: 'pi pi-file-pdf',
          command: () => handleExport('pdf'),
        },
      ],
    },
  ]

  return (
    <>
      <Button
        label="Export"
        icon="pi pi-download"
        loading={loading}
        disabled={disabled}
        outlined
        onClick={(e) => menuRef.current?.toggle(e)}
      />
      <Menu ref={menuRef} model={menuItems} popup />
    </>
  )
}
