// frontend/vue/primevue/minimal/src/components/common/ExportButton.vue
<template>
  <div class="export-button-wrapper">
    <Button
      type="button"
      :loading="loading"
      :disabled="disabled"
      icon="pi pi-download"
      label="Export"
      outlined
      severity="primary"
      @click="toggleMenu"
    />
    <Menu ref="menuRef" :model="menuItems" :popup="true" />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useNotificationStore } from '@/stores/notification'
import Button from 'primevue/button'
import Menu from 'primevue/menu'

const props = defineProps({
  exportFn: {
    type: Function,
    required: true,
  },
  filters: {
    type: Object,
    default: () => ({}),
  },
  disabled: {
    type: Boolean,
    default: false,
  },
})

const emit = defineEmits(['export-start', 'export-complete', 'export-error'])

const notificationStore = useNotificationStore()
const menuRef = ref()
const loading = ref(false)

const menuItems = computed(() => [
  {
    label: 'Export Format',
    items: [
      {
        label: 'Excel (.xlsx)',
        icon: 'pi pi-file-excel',
        command: () => handleExport('xlsx'),
      },
      {
        label: 'CSV (.csv)',
        icon: 'pi pi-file',
        command: () => handleExport('csv'),
      },
      {
        label: 'PDF Report (.pdf)',
        icon: 'pi pi-file-pdf',
        command: () => handleExport('pdf'),
      },
    ],
  },
])

function toggleMenu(event) {
  menuRef.value.toggle(event)
}

async function handleExport(format) {
  loading.value = true
  emit('export-start', format)

  try {
    const result = await props.exportFn(format, props.filters)
    notificationStore.showSuccess(`Exported successfully: ${result.fileName}`)
    emit('export-complete', result)
  } catch (error) {
    console.error('Export failed:', error)
    notificationStore.showError('Export failed. Please try again.')
    emit('export-error', error)
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.export-button-wrapper {
  display: inline-block;
}
</style>

// frontend/react/primereact/minimal/src/components/common/ExportButton.tsx
import { useState, useRef } from 'react'
import { Button } from 'primereact/button'
import { Menu } from 'primereact/menu'
import { MenuItem } from 'primereact/menuitem'
import { useNotificationStore } from '@/stores'

interface ExportButtonProps {
  exportFn: (format: string, filters: Record<string, any>) => Promise<{ success: boolean; fileName: string }>
  filters?: Record<string, any>
  disabled?: boolean
  onExportStart?: (format: string) => void
  onExportComplete?: (result: { success: boolean; fileName: string }) => void
  onExportError?: (error: Error) => void
}

export function ExportButton({
  exportFn,
  filters = {},
  disabled = false,
  onExportStart,
  onExportComplete,
  onExportError,
}: ExportButtonProps) {
  const [loading, setLoading] = useState(false)
  const menuRef = useRef<Menu>(null)
  const showSuccess = useNotificationStore((state) => state.showSuccess)
  const showError = useNotificationStore((state) => state.showError)

  const handleExport = async (format: string) => {
    setLoading(true)
    onExportStart?.(format)

    try {
      const result = await exportFn(format, filters)
      showSuccess(`Exported successfully: ${result.fileName}`)
      onExportComplete?.(result)
    } catch (error) {
      console.error('Export failed:', error)
      showError('Export failed. Please try again.')
      onExportError?.(error as Error)
    } finally {
      setLoading(false)
    }
  }

  const menuItems: MenuItem[] = [
    {
      label: 'Export Format',
      items: [
        {
          label: 'Excel (.xlsx)',
          icon: 'pi pi-file-excel',
          command: () => handleExport('xlsx'),
        },
        {
          label: 'CSV (.csv)',
          icon: 'pi pi-file',
          command: () => handleExport('csv'),
        },
        {
          label: 'PDF Report (.pdf)',
          icon: 'pi pi-file-pdf',
          command: () => handleExport('pdf'),
        },
      ],
    },
  ]

  return (
    <>
      <Button
        label="Export"
        icon="pi pi-download"
        loading={loading}
        disabled={disabled}
        outlined
        onClick={(e) => menuRef.current?.toggle(e)}
      />
      <Menu ref={menuRef} model={menuItems} popup />
    </>
  )
}
