// frontend/vue/vuetify/full/src/components/common/PasswordStrength.vue
<template>
  <div class="password-strength">
    <v-progress-linear
      :color="strengthColor"
      height="8"
      :model-value="strength"
      rounded
    />
    <div class="d-flex justify-space-between mt-1">
      <span class="text-caption" :class="`text-${strengthColor}`">
        {{ strengthLabel }}
      </span>
      <span class="text-caption text-medium-emphasis">
        {{ requirements }}
      </span>
    </div>
  </div>
</template>

<script setup>
  import { computed } from 'vue'

  const props = defineProps({
    password: {
      type: String,
      default: '',
    },
  })

  const checks = computed(() => {
    const p = props.password || ''
    return {
      length: p.length >= 8,
      uppercase: /[A-Z]/.test(p),
      lowercase: /[a-z]/.test(p),
      number: /[0-9]/.test(p),
      special: /[!@#$%^&*(),.?":{}|<>]/.test(p),
    }
  })

  const passedChecks = computed(() => {
    return Object.values(checks.value).filter(Boolean).length
  })

  const strength = computed(() => {
    return (passedChecks.value / 5) * 100
  })

  const strengthColor = computed(() => {
    if (passedChecks.value <= 2) return 'error'
    if (passedChecks.value <= 3) return 'warning'
    if (passedChecks.value <= 4) return 'info'
    return 'success'
  })

  const strengthLabel = computed(() => {
    if (passedChecks.value <= 2) return 'Weak'
    if (passedChecks.value <= 3) return 'Fair'
    if (passedChecks.value <= 4) return 'Good'
    return 'Strong'
  })

  const requirements = computed(() => {
    const missing = []
    if (checks.value.length === 0) missing.push('8+ chars')
    if (!checks.value.uppercase) missing.push('uppercase')
    if (!checks.value.lowercase) missing.push('lowercase')
    if (!checks.value.number) missing.push('number')
    if (!checks.value.special) missing.push('special char')

    if (missing.length === 0) return 'All requirements met'
    return `Missing: ${missing.join(', ')}`
  })
</script>

<style scoped>
.password-strength {
  margin-top: 4px;
}
</style>

// frontend-mui/src/components/common/PasswordStrength.tsx
import { useMemo } from 'react'
import { Box, LinearProgress, Typography } from '@mui/material'

interface PasswordStrengthProps {
  password: string
}

export function PasswordStrength({ password }: PasswordStrengthProps) {
  const checks = useMemo(() => {
    const p = password || ''
    return {
      length: p.length >= 8,
      uppercase: /[A-Z]/.test(p),
      lowercase: /[a-z]/.test(p),
      number: /[0-9]/.test(p),
      special: /[!@#$%^&*(),.?":{}|<>]/.test(p),
    }
  }, [password])

  const passedChecks = useMemo(() => {
    return Object.values(checks).filter(Boolean).length
  }, [checks])

  const strength = useMemo(() => {
    return (passedChecks / 5) * 100
  }, [passedChecks])

  const strengthColor = useMemo(() => {
    if (passedChecks <= 2) return 'error'
    if (passedChecks <= 3) return 'warning'
    if (passedChecks <= 4) return 'info'
    return 'success'
  }, [passedChecks])

  const strengthLabel = useMemo(() => {
    if (passedChecks <= 2) return 'Weak'
    if (passedChecks <= 3) return 'Fair'
    if (passedChecks <= 4) return 'Good'
    return 'Strong'
  }, [passedChecks])

  const requirements = useMemo(() => {
    const missing: string[] = []
    if (!checks.length) missing.push('8+ chars')
    if (!checks.uppercase) missing.push('uppercase')
    if (!checks.lowercase) missing.push('lowercase')
    if (!checks.number) missing.push('number')
    if (!checks.special) missing.push('special char')

    if (missing.length === 0) return 'All requirements met'
    return `Missing: ${missing.join(', ')}`
  }, [checks])

  return (
    <Box sx={{ mt: 0.5 }}>
      <LinearProgress
        variant="determinate"
        value={strength}
        color={strengthColor}
        sx={{ height: 8, borderRadius: 1 }}
      />
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mt: 0.5 }}>
        <Typography variant="caption" color={`${strengthColor}.main`}>
          {strengthLabel}
        </Typography>
        <Typography variant="caption" color="text.secondary">
          {requirements}
        </Typography>
      </Box>
    </Box>
  )
}
