// frontend-primereact/src/pages/Departments.tsx
import { useState, useEffect, useRef } from 'react'
import { DataTable } from 'primereact/datatable'
import { Column } from 'primereact/column'
import { Button } from 'primereact/button'
import { Dialog } from 'primereact/dialog'
import { InputText } from 'primereact/inputtext'
import { InputTextarea } from 'primereact/inputtextarea'
import { InputSwitch } from 'primereact/inputswitch'
import { Tag } from 'primereact/tag'
import { Toast } from 'primereact/toast'
import { ConfirmDialog } from '@/components'
import { useDepartmentStore } from '@/stores/departmentStore'
import { useNotificationStore } from '@/stores/notificationStore'
import type { Department, CreateDepartmentRequest, UpdateDepartmentRequest } from '@/types/department'

export default function Departments() {
  const toast = useRef<Toast>(null)
  const departments = useDepartmentStore((state) => state.departments)
  const loading = useDepartmentStore((state) => state.loading)
  const fetchDepartments = useDepartmentStore((state) => state.fetchDepartments)
  const createDepartment = useDepartmentStore((state) => state.createDepartment)
  const updateDepartment = useDepartmentStore((state) => state.updateDepartment)
  const deleteDepartment = useDepartmentStore((state) => state.deleteDepartment)

  const showNotification = useNotificationStore((state) => state.showNotification)

  const [dialogVisible, setDialogVisible] = useState(false)
  const [deleteDialogVisible, setDeleteDialogVisible] = useState(false)
  const [selectedDepartment, setSelectedDepartment] = useState<Department | null>(null)
  const [isEditing, setIsEditing] = useState(false)

  const [formData, setFormData] = useState<CreateDepartmentRequest & { isActive: boolean }>({
    name: '',
    code: '',
    description: '',
    isActive: true,
  })

  useEffect(() => {
    fetchDepartments()
  }, [fetchDepartments])

  const openCreateDialog = () => {
    setFormData({
      name: '',
      code: '',
      description: '',
      isActive: true,
    })
    setIsEditing(false)
    setDialogVisible(true)
  }

  const openEditDialog = (department: Department) => {
    setFormData({
      name: department.name,
      code: department.code,
      description: department.description || '',
      isActive: department.isActive,
    })
    setSelectedDepartment(department)
    setIsEditing(true)
    setDialogVisible(true)
  }

  const openDeleteDialog = (department: Department) => {
    setSelectedDepartment(department)
    setDeleteDialogVisible(true)
  }

  const handleSubmit = async () => {
    try {
      if (isEditing && selectedDepartment) {
        const updateData: UpdateDepartmentRequest = {
          name: formData.name,
          description: formData.description,
          isActive: formData.isActive,
        }
        await updateDepartment(selectedDepartment.id, updateData)
        showNotification('Department updated successfully', 'success')
      } else {
        await createDepartment(formData)
        showNotification('Department created successfully', 'success')
      }
      setDialogVisible(false)
    } catch (error: any) {
      showNotification(error.response?.data?.message || 'Operation failed', 'error')
    }
  }

  const handleDelete = async () => {
    if (selectedDepartment) {
      try {
        await deleteDepartment(selectedDepartment.id)
        showNotification('Department deleted successfully', 'success')
        setDeleteDialogVisible(false)
      } catch (error: any) {
        showNotification(error.response?.data?.message || 'Failed to delete department', 'error')
      }
    }
  }

  const statusTemplate = (department: Department) => (
    <Tag
      value={department.isActive ? 'Active' : 'Inactive'}
      severity={department.isActive ? 'success' : 'danger'}
    />
  )

  const actionsTemplate = (department: Department) => (
    <div className="flex gap-2">
      <Button
        icon="pi pi-pencil"
        rounded
        text
        severity="info"
        onClick={() => openEditDialog(department)}
      />
      <Button
        icon="pi pi-trash"
        rounded
        text
        severity="danger"
        onClick={() => openDeleteDialog(department)}
      />
    </div>
  )

  const dialogFooter = (
    <div className="flex justify-content-end gap-2">
      <Button label="Cancel" text onClick={() => setDialogVisible(false)} />
      <Button label={isEditing ? 'Update' : 'Create'} onClick={handleSubmit} />
    </div>
  )

  return (
    <div>
      <Toast ref={toast} />

      <div className="flex justify-content-between align-items-center mb-4">
        <div className="text-3xl font-bold">Departments</div>
        <Button label="Add Department" icon="pi pi-plus" onClick={openCreateDialog} />
      </div>

      <DataTable value={departments} loading={loading} paginator rows={10} stripedRows>
        <Column field="code" header="Code" sortable />
        <Column field="name" header="Name" sortable />
        <Column field="description" header="Description" />
        <Column field="isActive" header="Status" body={statusTemplate} sortable />
        <Column header="Actions" body={actionsTemplate} style={{ width: '120px' }} />
      </DataTable>

      <Dialog
        header={isEditing ? 'Edit Department' : 'Create Department'}
        visible={dialogVisible}
        onHide={() => setDialogVisible(false)}
        footer={dialogFooter}
        style={{ width: '500px' }}
      >
        <div className="flex flex-column gap-4">
          <div>
            <label htmlFor="code" className="block text-900 font-medium mb-2">
              Code
            </label>
            <InputText
              id="code"
              value={formData.code}
              onChange={(e) => setFormData({ ...formData, code: e.target.value })}
              className="w-full"
              disabled={isEditing}
            />
          </div>

          <div>
            <label htmlFor="name" className="block text-900 font-medium mb-2">
              Name
            </label>
            <InputText
              id="name"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="w-full"
            />
          </div>

          <div>
            <label htmlFor="description" className="block text-900 font-medium mb-2">
              Description
            </label>
            <InputTextarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              className="w-full"
              rows={3}
            />
          </div>

          {isEditing && (
            <div className="flex align-items-center gap-2">
              <InputSwitch
                checked={formData.isActive}
                onChange={(e) => setFormData({ ...formData, isActive: e.value ?? false })}
              />
              <label className="text-900 font-medium">Active</label>
            </div>
          )}
        </div>
      </Dialog>

      <ConfirmDialog
        visible={deleteDialogVisible}
        title="Delete Department"
        message={`Are you sure you want to delete department "${selectedDepartment?.name}"?`}
        confirmLabel="Delete"
        confirmSeverity="danger"
        onConfirm={handleDelete}
        onCancel={() => setDeleteDialogVisible(false)}
      />
    </div>
  )
}

// frontend/vue/primevue/full/src/pages/departments/index.vue
<template>
  <div class="departments-page">

    <!-- Departments Table -->
    <Card>
      <template #content>
        <DataTable
          v-model:filters="filters"
          class="departments-table"
          data-key="id"
          filter-display="row"
          :global-filter-fields="['code', 'name']"
          :loading="loading"
          paginator
          responsive-layout="scroll"
          :rows="10"
          :rows-per-page-options="[5, 10, 25, 50]"
          :value="departments"
        >
          <template #header>
            <div class="flex flex-wrap align-items-center justify-content-between gap-2">
              <IconField>
                <InputIcon class="pi pi-search" />
                <InputText
                  v-model="filters['global'].value"
                  class="w-20rem"
                  placeholder="Search departments..."
                />
              </IconField>
              <Button icon="pi pi-building" label="Add Department" @click="openCreateDialog" />
            </div>
          </template>

          <template #empty>
            <div class="table-empty">
              <i class="pi pi-building" />
              <span>No departments found</span>
            </div>
          </template>

          <Column field="code" header="Code" sortable style="min-width: 120px">
            <template #body="{ data }">
              <Tag severity="secondary" :value="data.code" />
            </template>
          </Column>

          <Column field="name" header="Name" sortable style="min-width: 200px" />

          <Column field="description" header="Description" style="min-width: 300px">
            <template #body="{ data }">
              {{ data.description || '-' }}
            </template>
          </Column>

          <Column field="isActive" header="Status" sortable style="min-width: 100px">
            <template #body="{ data }">
              <Tag
                :severity="data.isActive ? 'success' : 'secondary'"
                :value="data.isActive ? 'Active' : 'Inactive'"
              />
            </template>
          </Column>

          <Column field="createdAt" header="Created" sortable style="min-width: 150px">
            <template #body="{ data }">
              {{ formatDate(data.createdAt) }}
            </template>
          </Column>

          <Column header="Actions" style="min-width: 120px">
            <template #body="{ data }">
              <div class="action-buttons">
                <Button
                  v-tooltip.top="'Edit'"
                  icon="pi pi-pencil"
                  rounded
                  severity="info"
                  text
                  @click="openEditDialog(data)"
                />
                <Button
                  v-tooltip.top="'Delete'"
                  icon="pi pi-trash"
                  rounded
                  severity="danger"
                  text
                  @click="handleDelete(data)"
                />
              </div>
            </template>
          </Column>
        </DataTable>
      </template>
    </Card>

    <!-- Create/Edit Dialog -->
    <Dialog
      v-model:visible="dialogVisible"
      :header="editingDepartment ? 'Edit Department' : 'Create New Department'"
      modal
      :style="{ width: '32rem' }"
    >
      <div class="flex flex-column gap-3">
        <div class="flex flex-column gap-2 mb-4">
          <label for="code">Code *</label>
          <InputText
            id="code"
            v-model="form.code"
            class="w-full"
            :disabled="!!editingDepartment"
            :invalid="!!formErrors.code"
            placeholder="e.g., IT, HR, FIN"
          />
          <small v-if="formErrors.code" class="text-red-500">{{ formErrors.code }}</small>
        </div>

        <div class="flex flex-column gap-2 mb-4">
          <label for="name">Name *</label>
          <InputText
            id="name"
            v-model="form.name"
            class="w-full"
            :invalid="!!formErrors.name"
            placeholder="e.g., Information Technology"
          />
          <small v-if="formErrors.name" class="text-red-500">{{ formErrors.name }}</small>
        </div>

        <div class="flex flex-column gap-2 mb-4">
          <label for="description">Description</label>
          <Textarea
            id="description"
            v-model="form.description"
            class="w-full"
            placeholder="Optional description..."
            rows="3"
          />
        </div>

        <div v-if="editingDepartment" class="flex align-items-center gap-2">
          <ToggleSwitch id="isActive" v-model="form.isActive" />
          <label for="isActive">Status: {{ form.isActive ? 'Active' : 'Inactive' }}</label>
        </div>

      </div>
      <template #footer>
        <Button label="Cancel" severity="secondary" @click="closeDialog" />
        <Button
          :label="editingDepartment ? 'Update' : 'Create'"
          :loading="saving"
          @click="handleSubmit"
        />
      </template>
    </Dialog>
  </div>
</template>

<script setup>
  import { FilterMatchMode } from '@primevue/core/api'
  import Button from 'primevue/button'
  import Card from 'primevue/card'
  import Column from 'primevue/column'
  import DataTable from 'primevue/datatable'
  import Dialog from 'primevue/dialog'
  import IconField from 'primevue/iconfield'
  import InputIcon from 'primevue/inputicon'
  import InputText from 'primevue/inputtext'
  import Tag from 'primevue/tag'
  import Textarea from 'primevue/textarea'
  import ToggleSwitch from 'primevue/toggleswitch'
  import { computed, onMounted, reactive, ref } from 'vue'
  import { useConfirmDialog } from '@/composables/useConfirmDialog'
  import { useDepartmentStore } from '@/stores/department'
  import { useNotificationStore } from '@/stores/notification'

  const departmentStore = useDepartmentStore()
  const notificationStore = useNotificationStore()
  const { confirmDelete } = useConfirmDialog()

  const loading = ref(false)
  const saving = ref(false)
  const dialogVisible = ref(false)
  const editingDepartment = ref(null)

  const filters = ref({
    global: { value: null, matchMode: FilterMatchMode.CONTAINS },
  })

  const departments = computed(() => departmentStore.departments)

  const form = reactive({
    code: '',
    name: '',
    description: '',
    isActive: true,
  })

  const formErrors = reactive({
    code: '',
    name: '',
  })

  function formatDate (dateString) {
    if (!dateString) return '-'
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    })
  }

  function resetForm () {
    form.code = ''
    form.name = ''
    form.description = ''
    form.isActive = true
    for (const key of Object.keys(formErrors)) (formErrors[key] = '')
  }

  function openCreateDialog () {
    editingDepartment.value = null
    resetForm()
    dialogVisible.value = true
  }

  function openEditDialog (department) {
    editingDepartment.value = department
    form.code = department.code
    form.name = department.name
    form.description = department.description || ''
    form.isActive = department.isActive
    for (const key of Object.keys(formErrors)) (formErrors[key] = '')
    dialogVisible.value = true
  }

  function closeDialog () {
    dialogVisible.value = false
    editingDepartment.value = null
  }

  function validate () {
    let valid = true
    for (const key of Object.keys(formErrors)) (formErrors[key] = '')

    if (!form.code.trim()) {
      formErrors.code = 'Code is required'
      valid = false
    }

    if (!form.name.trim()) {
      formErrors.name = 'Name is required'
      valid = false
    }

    return valid
  }

  async function handleSubmit () {
    if (!validate()) return

    saving.value = true
    try {
      if (editingDepartment.value) {
        await departmentStore.updateDepartment(editingDepartment.value.id, {
          name: form.name,
          description: form.description,
          isActive: form.isActive,
        })
        notificationStore.success('Department updated successfully')
      } else {
        await departmentStore.createDepartment({
          code: form.code,
          name: form.name,
          description: form.description,
        })
        notificationStore.success('Department created successfully')
      }
      await departmentStore.fetchDepartments()
      closeDialog()
    } catch (error) {
      notificationStore.error(error.response?.data?.message || 'Operation failed')
    } finally {
      saving.value = false
    }
  }

  async function handleDelete (department) {
    const confirmed = await confirmDelete(department.name)
    if (!confirmed) return

    try {
      await departmentStore.deleteDepartment(department.id)
      notificationStore.success('Department deleted successfully')
      await departmentStore.fetchDepartments()
    } catch {
    // Error toast handled by store
    }
  }

  onMounted(async () => {
    loading.value = true
    try {
      await departmentStore.fetchDepartments()
    } finally {
      loading.value = false
    }
  })
</script>

<style scoped>
.departments-page {
  padding: 1rem;
}

.table-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 3rem;
  gap: 0.5rem;
  color: var(--p-text-muted-color);
}

.table-empty i {
  font-size: 3rem;
}

.action-buttons {
  display: flex;
  gap: 0.25rem;
}

.text-red-500 {
  color: var(--p-red-500);
}
</style>
